In [1]:
# Import series of helper function for the notebook
from Helper_functions import create_tensorboard_callback, plot_loss_curves, compare_historys

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

## Get a text dataset

The dataset we're going to be using is Kaggle's introduction to NLP dataset (text samples of Tweets labelled as disaster or not disaster)

In [2]:
import pandas as pd

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

train_data.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [3]:
train_data['text'][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

In [4]:
# Shuffle training dataframe
train_data_shuffled = train_data.sample(frac=1, random_state=42)
train_data_shuffled

,id,keyword,location,text,target
2644,3796,destruction,NaN,So you have a new weapon that can cause un-ima...,1
2227,3185,deluge,NaN,The f$&amp;@ing things I do for #GISHWHES Just...,0
5448,7769,police,UK,DT @georgegalloway: RT @Galloway4Mayor: ÛÏThe...,1
132,191,aftershock,NaN,Aftershock back to school kick off was great. ...,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma Children of Addicts deve...,0
...,...,...,...,...,...
5226,7470,obliteration,Merica!,@Eganator2000 There aren't many Obliteration s...,0
5390,7691,panic,NaN,just had a panic attack bc I don't have enough...,0
860,1242,blood,NaN,Omron HEM-712C Automatic Blood Pressure Monito...,0
7603,10862,NaN,NaN,Officials say a quarantine is in place at an A...,1
7270,10409,whirlwind,Stamford & Cork (& Shropshire),I moved to England five years ago today. What ...,1

In [5]:
# Test data
test_data.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [6]:
# Count of samples
train_data.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [7]:
# Let's visualize some random training examples
import random 
random_index = random.randint(0, len(train_data)-5) # Create random indexes
for row in train_data_shuffled[["text", "target"]][random_index:random_index+5].itertuples():
    _, text, target = row
    print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
    print(f"Text:\n{text}\n")
    print("---\n")

Target: 0 (not real disaster)
Text:
[GPV Wind] As of 06JST 6AUG: WNW 06JST 6AUG / E 12JST 6AUG / S 18JST 6AUG. http://t.co/l6jBjAj8dm

---

Target: 1 (real disaster)
Text:
APC Chieftain Tasks Dickson On N15b Floods Donation To Bayelsa http://t.co/LqGOe7psXp

---

Target: 1 (real disaster)
Text:
Saving the City in Old Town: The Proposed Demolition of 159 West Burton http://t.co/FJddx43Ewj @MessnerMatthew for @newcity

---

Target: 0 (not real disaster)
Text:
POTUS appoints Brig. Gen. Richard G. Kaiser as member of the Mississippi River Commission. Learn more about the MRC: http://t.co/vdUKcV7YJy

---

Target: 0 (not real disaster)
Text:
@myrtlegroggins &lt;gasp!&gt; I forgot Sunday! OMG

---

### Split data into training and validation sets
Since the test set has no labels and we need a way to evaluate our trained models, we'll split off some of the trianing data and create validation set.

In [109]:
from sklearn.model_selection import train_test_split

train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_data_shuffled["text"].to_numpy(),
                                                                            train_data_shuffled["target"].to_numpy(),
                                                                            test_size=0.1,
                                                                            random_state=42)

In [9]:
# checking the length
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [10]:
# first 10 training sentences and their labels
train_sentences[:10], train_labels

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0, 0, 1, ..., 1, 1, 0], dtype=int64))

## Converting text into numbers

There are two main techniques to convert text into numbers:

1. Text tokenization
2. Text embeddings

### Text tokenization

In [11]:
import tensorflow as tf 
from tensorflow.keras.layers import TextVectorization

text_vectorizer = TextVectorization(max_tokens=None, # how many words in the vocabulary (all of the different words in text)
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None,
                                    output_mode="int",
                                    output_sequence_length=None)

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [12]:
# Find average number of tokens (words) in training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [13]:
# Setup text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 15

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [14]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences)

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

In [15]:
# Create a sample sentence and tokenize it 
sample_sentence = "There's a flood in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=int64)>

In [16]:
# Choose a random sentence from the training dataset and tokenize it
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
    \n\nVectorized version:")
text_vectorizer([random_sentence])

Original text:
 August 5: Your daily horoscope: A relationship upheaval over the next few months may be disruptive but in the ... http://t.co/gk4uNPZNhN

Vectorized version:

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 407,  180,   33,  857,    1,    3, 4767,  562,   60,    2,  274,
         548, 1119,  133,   21]], dtype=int64)>

In [17]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary() # Get all of the unique words in our training data
top_5_words = words_in_vocab[:5] # get the most common words
bottom_5_words = words_in_vocab[-5:] # get the least common words
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"5 most common words: {top_5_words}")
print(f"5 least common words: {bottom_5_words}")

Number of words in vocab: 10000
5 most common words: ['', '[UNK]', 'the', 'a', 'in']
5 least common words: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']

## Creating an Embedding using an Embedding Layer

The parameters we care most about for our embedding layer:
* `input_dim` = the size of our vocabulary
* `output_dim` = the size of the output embedding vector, for example, a value of 100 would mean each token gets represented by a vector 100 long
* `input_length` = length of the sequences being passed to the embedding layer

In [18]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128,
                             input_length=max_length # how long is each input
                             )
embedding

In [19]:
# Get a random sentence from the training set
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
    \n\nEmbedded version:")

# Embed the random sentence (turn it into dense vectors of fixed size)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
 @tsunami_esh ?? hey Esh

Embedded version:

<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.04830763,  0.038241  ,  0.01093151, ..., -0.0499359 ,
          0.01962917,  0.01525576],
        [ 0.02624771, -0.03946833,  0.03683808, ...,  0.02680068,
          0.04824603, -0.04015223],
        [ 0.02641037,  0.01412496, -0.01945691, ...,  0.0284286 ,
         -0.00233296,  0.04209327],
        ...,
        [ 0.0009156 , -0.02032012,  0.04899535, ...,  0.00794094,
          0.04299357,  0.01951369],
        [ 0.0009156 , -0.02032012,  0.04899535, ...,  0.00794094,
          0.04299357,  0.01951369],
        [ 0.0009156 , -0.02032012,  0.04899535, ...,  0.00794094,
          0.04299357,  0.01951369]]], dtype=float32)>

In [20]:
# Check out a single token's embdedding
sample_embed[0][0], sample_embed[0][0].shape, random_sentence

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.04830763,  0.038241  ,  0.01093151, -0.00060578,  0.00531515,
         0.00242234, -0.00922297,  0.02914584,  0.01896203, -0.03481699,
         0.02810485, -0.00801905, -0.04192196,  0.01541467, -0.03206049,
         0.0430321 ,  0.02177156,  0.02908674, -0.03431033,  0.02288132,
        -0.01572211, -0.04943695,  0.01364528, -0.04547044,  0.00369425,
         0.01705236,  0.02431841,  0.03809862, -0.01032925,  0.0304767 ,
         0.0447912 ,  0.01089638,  0.0301295 ,  0.04739073,  0.01391295,
         0.01828268, -0.04679115, -0.02937611,  0.03066209,  0.01721797,
        -0.04023545,  0.01283355, -0.04911286, -0.01473631, -0.03016608,
         0.00714669,  0.03987012, -0.04898126, -0.02484768, -0.04513328,
        -0.0338859 , -0.01645876, -0.02572504,  0.046011  ,  0.00506729,
        -0.00998662, -0.02658644, -0.00856403,  0.00587625, -0.01660714,
         0.04574328,  0.01260788,  0.04167553,  0.00056469,  0.01699143,
        -0.0462333 , -0.00012332, -0.03502989, -0.0364972 ,  0.00818031,
        -0.02763556, -0.00752402,  0.01186955,  0.04605523,  0.00816138,
        -0.01581221, -0.03017939,  0.04044357,  0.01022018,  0.02581594,
         0.03998442,  0.01407519, -0.00052039,  0.04862908, -0.03503376,
         0.01723834, -0.0018594 , -0.0168756 ,  0.02157504,  0.01320012,
         0.00105771, -0.04960501,  0.00916155, -0.04227487,  0.00302352,
         0.02693865,  0.02682117,  0.00657971,  0.03793855,  0.03060297,
        -0.00461447, -0.02191923, -0.02310468, -0.01556659,  0.00884851,
        -0.00655261, -0.01820267,  0.03781975,  0.04016053,  0.0013381 ,
        -0.00666683, -0.01130763,  0.04092704,  0.04614634,  0.0123709 ,
         0.0104018 ,  0.03728873, -0.01483471, -0.03973567, -0.0342462 ,
         0.04637914, -0.04303551,  0.02135489,  0.02863187,  0.02111913,
        -0.0499359 ,  0.01962917,  0.01525576], dtype=float32)>,
 TensorShape([128]),
 '@tsunami_esh ?? hey Esh')

## Modelling a text dataset (running a series of experiments)

Now we've a got way to turn our text sequences into numbers, it's time to start building a series of modelling experiments.

We'll start with a baseline and move on from there

* Model 0: Naive Bayes (baseline).
* Model 1: Feed-Forward neural network (dense model)
* Model 2: LSTM model (RNN)
* Model 3: GRU model (RNN)\
* Model 4: Bidirectional-LSTM model (RNN)
* Model 5: 1D Convolutional Neural Network (CNN)
* Model 6: TensorFlow Hub pretrained feature extractor (using transfer learning for NLP)
* Model 7: Same as model 6 with 10% of training data.

### Model 0: Getting a baseline

As with all machine learning modelling experiments, it's important to create as baseline model so you have got a benchmark for future experiments to build upon.

To create our baseline, we'll use sklearn's multinomial naive bayes using the TF-IDF formula to convert our words to numbers.

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
    ("tfidf", TfidfVectorizer()), # convert words to numbers 
    ("clf", MultinomialNB()) # model the text
])

# Fit the pipeline to the training data
model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [22]:
# Evaluate our baseline model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%")

Our baseline model achieves an accuracy of: 79.27%

In [23]:
# Make predictions 
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

### Creating an evaluation function for our model experiments

In [24]:
# Function to evaluate: accuracy, precision, recall and f1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
    """
    Calculates model accuracy, precision, recall and f1 score of a binary classification model.

    """
    # Calculate model accuracy 
    model_accuracy = accuracy_score(y_true, y_pred) * 100
    # Calculate model precision , recall and f1-score using "weighted" average
    model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
    model_results = {"accuracy": model_accuracy,
                     "precision": model_precision,
                     "recall": model_recall,
                     "f1": model_f1}
    return model_results

In [25]:
# Get baseline result
baseline_results = calculate_results(y_true=val_labels,
                                     y_pred=baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

### Model 1: A simple dense model

In [26]:
# BUild model with the Funcitonal API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string) # inputs are 1-dimensional strings
x = text_vectorizer(inputs) # turn the input text into numbers
x = embedding(x) # embedding of the numberized inputs
x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x) # output layers 
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [27]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 global_average_pooling1d (  (None, 128)               0
 GlobalAveragePooling1D)

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (4.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [29]:
val_sentences.shape, val_labels.shape

((762,), (762,))

In [30]:
# fit the model
model_1_history = model_1.fit(x=train_sentences,
                              y=train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

215/215 [==============================] - 5s 17ms/step - loss: 0.6151 - accuracy: 0.6819 - val_loss: 0.5388 - val_accuracy: 0.7651
Epoch 2/5
215/215 [==============================] - 3s 16ms/step - loss: 0.4441 - accuracy: 0.8139 - val_loss: 0.4711 - val_accuracy: 0.7874
Epoch 3/5
215/215 [==============================] - 3s 15ms/step - loss: 0.3497 - accuracy: 0.8599 - val_loss: 0.4619 - val_accuracy: 0.7927
Epoch 4/5
215/215 [==============================] - 3s 15ms/step - loss: 0.2868 - accuracy: 0.8902 - val_loss: 0.4660 - val_accuracy: 0.7874
Epoch 5/5
215/215 [==============================] - 3s 14ms/step - loss: 0.2397 - accuracy: 0.9088 - val_loss: 0.4772 - val_accuracy: 0.7848

In [31]:
# Check the results
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 2ms/step - loss: 0.4772 - accuracy: 0.7848

[0.47718551754951477, 0.7847769260406494]

In [32]:
# Make some predictions and evalutate those
model_1_pred_probs = model_1.predict(val_sentences)
model_1_pred_probs.shape

24/24 [==============================] - 0s 2ms/step

(762, 1)

In [33]:
model_1_pred_probs[0]

array([0.36390585], dtype=float32)

In [34]:
# Convert model prediciton probabilities  to label format
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:20]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1.], dtype=float32)>

In [35]:
# Calculate our model_1 results
model_1_results = calculate_results(y_true=val_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 78.4776902887139,
 'precision': 0.7895833902086796,
 'recall': 0.7847769028871391,
 'f1': 0.7817499108999565}

## Visualizing learned mebeddings

In [36]:
# Get the vocabulary from the text vectorization layer
words_in_vocab = text_vectorizer.get_vocabulary()
len(words_in_vocab), words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [37]:
# model 1 summary
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 global_average_pooling1d (  (None, 128)               0
 GlobalAveragePooling1D)

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (4.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [38]:
# Get tghe weight matrix of embedding layer
# (these are the numerical representations of each token in our training, which have been learned for ~5 epochs)
embed_weights = model_1.get_layer("embedding").get_weights()[0]
embed_weights.shape

(10000, 128)

In [39]:
# Create mebedding files (we got this from TensorFlow's word embedding documnetation)
import io
out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(words_in_vocab):
    if index == 0:
        continue # Skip 0, it's padding.
    vec = embed_weights[index]
    out_v.write('\t'.join([str(x) for x in vec]) + "\n")
    out_m.write(word + "\n")
out_v.close()
out_m.close()

## Recurrent Neural Networks (RNN's)

RNN's are useful for sequential data.

The premise of a recurrent neural network is to use the representation of a previous input to aid the representation of a later input.

### Model 2: LSTM

Our structure of an RNN typically looks like this:

```
Input (txt) -> Tokenize -> Embedding -> Layers (RNNs/Dense) -> Output (label probability)
```

In [40]:
# Create an LSTM model
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)
x = layers.LSTM(64, return_sequences=True)(x) # when you're stacking RNN cells together , you need to set return_sequences=True
# print(x.shape)
x = layers.LSTM(64)(x)
# print(x.shape)
# x = layers.Dense(64, activation="relu")(x)
# print(x.shape)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

In [41]:
# Get a summary()
model_2.summary()

Model: "model_2_LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_2 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 lstm (LSTM)                 (None, 15, 64)            49408

 lstm_1 (LSTM)               (None, 64)                33024

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1362497 (5.20 MB)
Trainable params: 1362497 (5.20 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [42]:
# Compile the model
model_2.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [43]:
# Fit the model
model_2.history = model_2.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 10s 28ms/step - loss: 0.2219 - accuracy: 0.9196 - val_loss: 0.5712 - val_accuracy: 0.7822
Epoch 2/5
215/215 [==============================] - 5s 22ms/step - loss: 0.1588 - accuracy: 0.9416 - val_loss: 0.6755 - val_accuracy: 0.7835
Epoch 3/5
215/215 [==============================] - 5s 22ms/step - loss: 0.1283 - accuracy: 0.9514 - val_loss: 0.6839 - val_accuracy: 0.7795
Epoch 4/5
215/215 [==============================] - 5s 23ms/step - loss: 0.1056 - accuracy: 0.9615 - val_loss: 0.8163 - val_accuracy: 0.7874
Epoch 5/5
215/215 [==============================] - 5s 22ms/step - loss: 0.0893 - accuracy: 0.9635 - val_loss: 1.0645 - val_accuracy: 0.7769

In [44]:
# Make predictions with LSTM model
model_2_pred_probs = model_2.predict(val_sentences)
model_2_pred_probs[:10]

24/24 [==============================] - 1s 6ms/step

array([[1.9407965e-02],
       [8.8117331e-01],
       [9.9990129e-01],
       [6.3445039e-02],
       [1.3052749e-04],
       [9.9979979e-01],
       [9.8667806e-01],
       [9.9991387e-01],
       [9.9989831e-01],
       [2.7407765e-01]], dtype=float32)

In [45]:
# Convert model 2 pred probs to labels
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

In [46]:
# Calculate model 2 results
model_2_results = calculate_results(y_true=val_labels,
                                    y_pred=model_2_preds)
model_2_results

{'accuracy': 77.69028871391076,
 'precision': 0.7766466003315282,
 'recall': 0.7769028871391076,
 'f1': 0.7762334961702412}

In [47]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

### Model 3: GRU

Another popular and effective RNN component is the GRU or gated recurrent unit.
The GRU cell has similar features to an LSTM cell but but has less parameters.

In [48]:
# Buld an RNN using the GRU cell
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GRU(64)(x)
# x = layers.GRU(64, return_sequences=True)(x)
# x = layers.LSTM(64, return_sequences=True)(x)
# x = layers.GRU(64, return_sequences=True)(x)
# x = layers.Dense(64, activation="relu")(x)
# x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_3 = tf.keras.Model(inputs, outputs, name="model_3_GRU")

In [49]:
model_3.summary()

Model: "model_3_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 gru (GRU)                   (None, 64)                37248

 dense_2 (Dense)             (None, 1)                 65

=================================================================
Total params: 1317313 (5.03 MB)
Trainable params: 1317313 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [50]:
# Compile the model
model_3.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [51]:
# Fit the model
model_3_history = model_3.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 7s 22ms/step - loss: 0.1604 - accuracy: 0.9381 - val_loss: 0.7647 - val_accuracy: 0.7822
Epoch 2/5
215/215 [==============================] - 4s 18ms/step - loss: 0.0858 - accuracy: 0.9673 - val_loss: 0.8632 - val_accuracy: 0.7743
Epoch 3/5
215/215 [==============================] - 4s 17ms/step - loss: 0.0728 - accuracy: 0.9736 - val_loss: 0.8828 - val_accuracy: 0.7848
Epoch 4/5
215/215 [==============================] - 4s 18ms/step - loss: 0.0633 - accuracy: 0.9761 - val_loss: 1.1320 - val_accuracy: 0.7743
Epoch 5/5
215/215 [==============================] - 4s 19ms/step - loss: 0.0536 - accuracy: 0.9759 - val_loss: 1.1470 - val_accuracy: 0.7795

In [52]:
# Make some predictions with our GRU model
model_3_pred_probs = model_3.predict(val_sentences)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 4ms/step

array([[8.07931588e-04],
       [9.73333418e-01],
       [9.99910474e-01],
       [6.83313161e-02],
       [1.16060255e-04],
       [9.99756098e-01],
       [8.34796846e-01],
       [9.99953806e-01],
       [9.99916673e-01],
       [9.08600688e-01]], dtype=float32)

In [53]:
# Convert model 3 pred probs to labels
model_3_preds = tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

In [54]:
# calculate model 3 results
model_3_results = calculate_results(y_true=val_labels,
                                    y_pred=model_3_preds)
model_3_results

{'accuracy': 77.95275590551181,
 'precision': 0.7813761276529175,
 'recall': 0.7795275590551181,
 'f1': 0.7775281328700309}

### Model 4: Bidirectional RNN
Normal RNN's go from left to right (just like you'd read an English sentence) however, a bidirectional RNN goes left to right also.

In [55]:
# Build a bidirectional RNN in TensorFlow
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
# x = layers.Bidirectional(layers.LSTM(64, return_sequences=True))(x)
x = layers.Bidirectional(layers.LSTM(64))(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_4 = tf.keras.Model(inputs, outputs, name="model_4_bidirectional")

In [56]:
# Get a summary
model_4.summary()

Model: "model_4_bidirectional"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_4 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 bidirectional (Bidirection  (None, 128)               98816
 al)

 dense_3 (Dense)             (None, 1)                 129

=================================================================
Total params: 1378945 (5.26 MB)
Trainable params: 1378945 (5.26 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [57]:
# Compile model
model_4.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [58]:
# Fit the model
model_4_hisrtory = model_4.fit(train_sentences,
                               train_labels,
                               epochs=5,
                               validation_data=(val_sentences, val_labels)
                               )

Epoch 1/5
215/215 [==============================] - 9s 26ms/step - loss: 0.1012 - accuracy: 0.9723 - val_loss: 0.8979 - val_accuracy: 0.7782
Epoch 2/5
215/215 [==============================] - 5s 21ms/step - loss: 0.0510 - accuracy: 0.9769 - val_loss: 1.0752 - val_accuracy: 0.7585
Epoch 3/5
215/215 [==============================] - 4s 21ms/step - loss: 0.0489 - accuracy: 0.9791 - val_loss: 1.2568 - val_accuracy: 0.7651
Epoch 4/5
215/215 [==============================] - 4s 21ms/step - loss: 0.0432 - accuracy: 0.9797 - val_loss: 1.3855 - val_accuracy: 0.7651
Epoch 5/5
215/215 [==============================] - 4s 20ms/step - loss: 0.0494 - accuracy: 0.9784 - val_loss: 1.4539 - val_accuracy: 0.7651

In [59]:
# Make predicitons with our bidirectional model
model_4_pred_probs = model_4.predict(val_sentences) 
model_4_pred_probs[:10]

24/24 [==============================] - 1s 4ms/step

array([[4.1831745e-04],
       [7.8175199e-01],
       [9.9990004e-01],
       [1.8466020e-01],
       [2.2497485e-05],
       [9.9887991e-01],
       [8.9283741e-01],
       [9.9997556e-01],
       [9.9990827e-01],
       [9.9947697e-01]], dtype=float32)

In [60]:
# Convert pred probs to pred labels
model_4_preds = tf.squeeze(tf.round(model_4_pred_probs))
model_4_preds[:10]

In [61]:
# Calculate the results of our bidirectional model
model_4_results = calculate_results(y_true=val_labels,
                                    y_pred=model_4_preds)
model_4_results

{'accuracy': 76.50918635170603,
 'precision': 0.7650786674444272,
 'recall': 0.7650918635170604,
 'f1': 0.7639596899608797}

### Convolution Neural Networks for Text (and other types of sequences)

We've used CNNs for images are typically 2D (height x width)... however, our text data is 1D.
Previously we've Conv2D for our image data but now we're going to use Conv1D.
The typical structure of a COnv1D model for sequences (in our case text)

```
Inputs (text) -> Tokenization -> Embedding -> Layer(s) (typically Conv1D + pooling) -> Outputs (class probabilities)
```

### Model 5: Conv1D

In [62]:
# Test out our embedding layer, Con1D layer and max pooling 
from tensorflow.keras import layers
embedding_test = embedding(text_vectorizer(["this is a test sentence"]))
conv_1d = layers.Conv1D(filters=32,
                        kernel_size=5,
                        strides=1, # default  
                        activation="relu",
                        padding="same")
conv_1d_output = conv_1d(embedding_test) # pass test embedding through conv1d layer
max_pool = layers.GlobalMaxPool1D()
max_pool_output = max_pool(conv_1d_output) 
embedding_test.shape, conv_1d_output.shape, max_pool_output.shape

(TensorShape([1, 15, 128]), TensorShape([1, 15, 32]), TensorShape([1, 32]))

In [63]:
# Create 1-dimensional convolutional layer to model sequence
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.Conv1D(filters=64, kernel_size=5, strides=1, activation="relu", padding="valid")(x)
x = layers.GlobalMaxPool1D()(x)
# x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_5 = tf.keras.Model(inputs, outputs, name="model_5_Conv1D")

# Compile Conv1D
model_5.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Get a summary of our Conv1D model
model_5.summary()

Model: "model_5_Conv1D"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_5 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 conv1d_1 (Conv1D)           (None, 11, 64)            41024

 global_max_pooling1d_1 (Gl  (None, 64)                0
 obalMaxPooling1D)

 dense_4 (Dense)             (None, 1)                 65

=================================================================
Total params: 1321089 (5.04 MB)
Trainable params: 1321089 (5.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [64]:
#  Fit the model
model_5_history = model_5.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 5s 18ms/step - loss: 0.1251 - accuracy: 0.9616 - val_loss: 0.8648 - val_accuracy: 0.7795
Epoch 2/5
215/215 [==============================] - 4s 17ms/step - loss: 0.0739 - accuracy: 0.9724 - val_loss: 1.0234 - val_accuracy: 0.7703
Epoch 3/5
215/215 [==============================] - 3s 16ms/step - loss: 0.0600 - accuracy: 0.9745 - val_loss: 1.1776 - val_accuracy: 0.7572
Epoch 4/5
215/215 [==============================] - 3s 14ms/step - loss: 0.0553 - accuracy: 0.9781 - val_loss: 1.2107 - val_accuracy: 0.7572
Epoch 5/5
215/215 [==============================] - 3s 13ms/step - loss: 0.0523 - accuracy: 0.9778 - val_loss: 1.2127 - val_accuracy: 0.7559

In [65]:
# Make some predictions with our Conv1D model
model_5_pred_probs = model_5.predict(val_sentences)
model_5_pred_probs[:10]

24/24 [==============================] - 0s 2ms/step

array([[3.1320527e-01],
       [8.9672327e-01],
       [9.9995136e-01],
       [7.2767012e-02],
       [2.5530636e-07],
       [9.9848622e-01],
       [9.7282487e-01],
       [9.9999464e-01],
       [9.9999964e-01],
       [9.1752195e-01]], dtype=float32)

In [66]:
# Convert model 5 pred probs to labels
model_5_preds = tf.squeeze(tf.round(model_5_pred_probs))
model_5_preds[:10]

In [67]:
# Evaluate model 5 predicitons
model_5_results = calculate_results(y_true=val_labels,
                                    y_pred=model_5_preds)
model_5_results

{'accuracy': 75.59055118110236,
 'precision': 0.7554928716129209,
 'recall': 0.7559055118110236,
 'f1': 0.7551731193392051}

In [68]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

## Model 6: TensorFlow Hub Pretrained sentence encoder

Now we've built a few of our models, let's try and use transfer learning for NLP, specifically using TensorFlow Hub's universal sentence encoder

In [69]:
import tensorflow_hub as hub

embed = hub.load("https://www.kaggle.com/models/google/universal-sentence-encoder/TensorFlow2/universal-sentence-encoder/2")
embed_samples = embed([sample_sentence,
                       "When you can the universal sentence encoder on a sentence, it turns it into numbers."])

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_estimator\python\estimator\util.py:74: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\saved_model_module.py:40: The name tf.saved_model.constants.LEGACY_INIT_OP_KEY is deprecated. Please use tf.compat.v1.saved_model.constants.LEGACY_INIT_OP_KEY instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

ValueError: Trying to load a model of incompatible/unknown type. 'C:\Users\Priyesh\AppData\Local\Temp\tfhub_modules\01b27d6b983e268d7ade6823c2452458cf1a12c4' contains neither 'saved_model.pb' nor 'saved_model.pbtxt'.

In [ ]:
embed_samples[0].shape

NameError: name 'embed_samples' is not defined

In [70]:
# Create a keras layer using the USE pretrained layer from tensorflow hub
sentence_encoder_layer = hub.KerasLayer("https://www.kaggle.com/models/google/universal-sentence-encoder/TensorFlow2/universal-sentence-encoder/2", 
                                        input_shape=[],
                                        dtype=tf.string,
                                        trainable=False,
                                        name="USE")

ValueError: Trying to load a model of incompatible/unknown type. 'C:\Users\Priyesh\AppData\Local\Temp\tfhub_modules\01b27d6b983e268d7ade6823c2452458cf1a12c4' contains neither 'saved_model.pb' nor 'saved_model.pbtxt'.

In [71]:
# Create model using the Sequential API
model_6 = tf.keras.Sequential([
    sentence_encoder_layer,
    layers.Dense(64, activation="relu"),
    layers.Dense(1, activation="sigmoid")
], name="model_6_USE")

# Compile 
model_6.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

model_6.summary()

NameError: name 'sentence_encoder_layer' is not defined

In [72]:
# Train a classifier on top of USE pretrained embeddings
model_6_history = model_6.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels),
                              )

NameError: name 'model_6' is not defined

In [73]:
# make predictions with USE TF Hub model
model_6_pred_probs = model_6.predict(val_sentences)
model_6_pred_probs[:10]

NameError: name 'model_6' is not defined

In [74]:
# Convert prediction probabilities to labels 
model_6_preds = tf.squeeze(tf.round(model_6_pred_probs))
model_6_preds[:10]

NameError: name 'model_6_pred_probs' is not defined

In [75]:
# Calculate model 6 performance metrics
model_6_results = calculate_results(y_true=val_labels,
                                    y_pred=model_6_preds)
model_6_results

NameError: name 'model_6_preds' is not defined

In [76]:
len(train_data_shuffled)

7613

## Model 7: TF Hub Pretrained USE but with 10% of training data
Transfer learning really helps when you don't have a large dataset.
To see how our model performs on a smaller dataset, let's replicate model_6 except we'll train it on 10% of the data.

In [77]:
# Create subsets of 10% of the training data
train_10_percent = train_data_shuffled[["text", "target"]].sample(frac=0.1, random_state=42)
train_sentences_10_percent = train_10_percent["text"].to_list()
train_labels_10_percent = train_10_percent["target"].to_list()
len(train_sentences_10_percent), len(train_labels_10_percent)

(761, 761)

In [78]:
# Check the number of targets in our subset of data
train_10_percent["target"].value_counts()

target
0    413
1    348
Name: count, dtype: int64

In [79]:
train_data_shuffled["target"].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [80]:
# Let's built a model the same as model_6
model_7 = tf.keras.models.clone_model(model_6)

# Compile the model
model_7.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Get a summary 
model_7.summary()

NameError: name 'model_6' is not defined

In [81]:
# Fit the model to the 10% training data subsets
model_7_history = model_7.fit(train_sentences_10_percent,
                              train_labels_10_percent,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

NameError: name 'model_7' is not defined

In [82]:
# Make precitions with the model trained on 10% of the data
model_7_pred_probs = model_7.predict(val_sentences)
model_7_pred_probs[:10]

NameError: name 'model_7' is not defined

In [83]:
# Turn pred probs into labels
model_7_preds = tf.squeeze(tf.round(model_7_pred_probs))
model_7_preds[:10]

NameError: name 'model_7_pred_probs' is not defined

In [84]:
# Evaluate model_7 predictions
model_7_results = calculate_results(y_true=val_labels,
                                    y_pred=model_7_preds)
model_7_results

NameError: name 'model_7_preds' is not defined

In [85]:
model_6_results

NameError: name 'model_6_results' is not defined

In [86]:
# Making a better dataset split (no data leakage)
train_10_percent_split = int(0.1 * len(train_sentences))
train_sentences_10_percent = train_sentences[:train_10_percent_split]
train_labels_10_percent = train_labels[:train_10_percent_split]
len(train_labels_10_percent)

685

**Note:** Be very careful when creating training/val/test splits that you don't leak data across the datasets, otherwise your model evaluation metrics will be wrong. If something looks too good to be true (a model trained on 10% of data outperforming the same model trained on 100% of data) trust your gut and go back through to find where the error may lie.

In [87]:
import numpy as np
pd.Series(np.array(train_labels_10_percent)).value_counts()

0    406
1    279
Name: count, dtype: int64

## Comparing the performance of each of our models

In [88]:
# Combine model results into a DataFrame
all_model_results = pd.DataFrame({"baseline": baseline_results,
                                  "1_simple_dense": model_1_results,
                                  "2_lstm": model_2_results,
                                  "3_gru": model_3_results,
                                  "4_bidirectional": model_4_results,
                                  "5_conv1d": model_5_results,
                                  "6_tf_hub_use_encoder": model_6_results,
                                  "7_tf_hub_use_encoder_10_percent": model_7_results})
all_model_results = all_model_results.transpose()
all_model_results

NameError: name 'model_6_results' is not defined

In [89]:
# Reduce the accuracy to the same scale as other metrics
all_model_results["accuracy"] = all_model_results["accuracy"] / 100
all_model_results

NameError: name 'all_model_results' is not defined

In [90]:
# Plot and compare all of the model
all_model_results.plot(kind="bar", figsize=(10, 7)).legend(bbox_to_anchor=(1.0, 1.0));

NameError: name 'all_model_results' is not defined

## Saving and loading a trained model

In [91]:
# Save TF Hub sentence encoder model to HDF5 format
model_6.save("model_6.h5")

NameError: name 'model_6' is not defined

In [92]:
# Load model with custom Hub layer (required HDF5 format)
import tensorflow_hub as hub
loaded_model_6 = tf.keras.models.load_model("model_6.h5",
                                            custom_objects={"KerasLayer": hub.KerasLayer})

OSError: No file or directory found at model_6.h5

In [93]:
# how does our loaded model perform?
loaded_model_6.evaluate(val_sentences, val_labels)

NameError: name 'loaded_model_6' is not defined

In [94]:
# Save TF hub sentence encoder model to SavedModel format (default)
model_6.save("model_6_saved_model_format")

NameError: name 'model_6' is not defined

In [95]:
# Load in a model from the saved model format
import tensorflow as tf
loaded_model_6_savedModel_format = tf.keras.models.load_model("model_6_saved_model_format")

In [96]:
loaded_model_6_savedModel_format.evaluate(val_sentences, val_labels)

24/24 [==============================] - 1s 7ms/step - loss: 0.4290 - accuracy: 0.8163

[0.42901867628097534, 0.8162729740142822]

### Finding the most wrong examples

* If our best model still isn't perfect, what examples is it getting wrong?
* And of these wrong examples which ones is it getting most wrong (those will prediction probabilities closest to the opposite class)

For example if a sample should have a label of 0 but our model predicts a prediction probability of 0.999 (really close to 1) and vice versa.

In [97]:
# Importing previously trained model from Google Storage
model_6_pretrained = tf.keras.models.load_model("model_6_saved_model_format")
model_6_pretrained.evaluate(val_sentences, val_labels)

24/24 [==============================] - 1s 11ms/step - loss: 0.4290 - accuracy: 0.8163

[0.42901867628097534, 0.8162729740142822]

In [98]:
# Make predictions with the loaded model from GS
model_6_pretrained_pred_probs = model_6_pretrained.predict(val_sentences)
model_6_pretrained_preds = tf.squeeze(tf.round(model_6_pretrained_pred_probs))
model_6_pretrained_preds[:10] # these should be in label format

24/24 [==============================] - 1s 6ms/step

In [99]:
# Create DataFrame with validation sentences, validation labels and best performing model Predictions
val_df = pd.DataFrame({"text": val_sentences,
                       "target": val_labels,
                       "pred": model_6_pretrained_preds,
                       "pred_prob": tf.squeeze(model_6_pretrained_pred_probs)})
val_df.head()

                                                text  target  pred  pred_prob
0  DFR EP016 Monthly Meltdown - On Dnbheaven 2015...       0   0.0   0.137032
1  FedEx no longer to transport bioterror germs i...       0   1.0   0.769151
2  Gunmen kill four in El Salvador bus attack: Su...       1   1.0   0.987962
3  @camilacabello97 Internally and externally scr...       1   0.0   0.195132
4  Radiation emergency #preparedness starts with ...       1   1.0   0.726143

In [100]:
# Find the wrong predictions and sort by prediction probabilities
most_wrong = val_df[val_df["target"] != val_df["pred"]].sort_values("pred_prob", ascending=False)
most_wrong[:10] # these are false positives

,text,target,pred,pred_prob
31,? High Skies - Burning Buildings ? http://t.co...,0,1.0,0.905810
759,FedEx will no longer transport bioterror patho...,0,1.0,0.884161
49,@madonnamking RSPCA site multiple 7 story high...,0,1.0,0.841931
393,@SonofLiberty357 all illuminated by the bright...,0,1.0,0.840570
251,@AshGhebranious civil rights continued in the ...,0,1.0,0.831715
209,Ashes 2015: AustraliaÛªs collapse at Trent Br...,0,1.0,0.809430
109,[55436] 1950 LIONEL TRAINS SMOKE LOCOMOTIVES W...,0,1.0,0.797058
1,FedEx no longer to transport bioterror germs i...,0,1.0,0.769151
474,My phone looks like it was in a car ship airpl...,0,1.0,0.766639
698,åÈMGN-AFRICAå¨ pin:263789F4 åÈ Correction: Ten...,0,1.0,0.751702

In [101]:
most_wrong.tail() # these are false negatives

,text,target,pred,pred_prob
233,I get to smoke my shit in peace,1,0.0,0.043511
38,Why are you deluged with low self-image? Take ...,1,0.0,0.040948
411,@SoonerMagic_ I mean I'm a fan but I don't nee...,1,0.0,0.040052
244,Reddit Will Now QuarantineÛ_ http://t.co/pkUA...,1,0.0,0.030203
23,Ron &amp; Fez - Dave's High School Crush https...,1,0.0,0.026484

In [102]:
# Check the false postives (model predicted 1 when should've been 0)
import pandas as pd
for row in most_wrong[:10].itertuples():
    _, text, target, pred, pred_prob = row
    print(f"Target: {target}, Pred: {pred}, Prob: {pred_prob}")
    print(f"Text:\n{text}\n")
    print("----\n")

Target: 0, Pred: 1.0, Prob: 0.9058102965354919
Text:
? High Skies - Burning Buildings ? http://t.co/uVq41i3Kx2 #nowplaying

----

Target: 0, Pred: 1.0, Prob: 0.8841612935066223
Text:
FedEx will no longer transport bioterror pathogens in wake of anthrax lab mishaps http://t.co/lHpgxc4b8J

----

Target: 0, Pred: 1.0, Prob: 0.8419314622879028
Text:
@madonnamking RSPCA site multiple 7 story high rise buildings next to low density character residential in an area that floods

----

Target: 0, Pred: 1.0, Prob: 0.8405700922012329
Text:
@SonofLiberty357 all illuminated by the brightly burning buildings all around the town!

----

Target: 0, Pred: 1.0, Prob: 0.8317149877548218
Text:
@AshGhebranious civil rights continued in the 60s. And what about trans-generational trauma? if anything we should listen to the Americans.

----

Target: 0, Pred: 1.0, Prob: 0.8094304800033569
Text:
Ashes 2015: AustraliaÛªs collapse at Trent Bridge among worst in history: England bundled out Australia for 60 ... http://t.co/t5TrhjUAU0

----

Target: 0, Pred: 1.0, Prob: 0.7970582842826843
Text:
[55436] 1950 LIONEL TRAINS SMOKE LOCOMOTIVES WITH MAGNE-TRACTION INSTRUCTIONS http://t.co/xEZBs3sq0y http://t.co/C2x0QoKGlY

----

Target: 0, Pred: 1.0, Prob: 0.7691510915756226
Text:
FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday

----

Target: 0, Pred: 1.0, Prob: 0.7666390538215637
Text:
My phone looks like it was in a car ship airplane accident. Terrible

----

Target: 0, Pred: 1.0, Prob: 0.7517023086547852
Text:
åÈMGN-AFRICAå¨ pin:263789F4 åÈ Correction: Tent Collapse Story: Correction: Tent Collapse story åÈ http://t.co/fDJUYvZMrv @wizkidayo

----

In [103]:
# Check the false negatives (model predicted 0 when should've been 1)
import pandas as pd
for row in most_wrong[:-10].itertuples():
    _, text, target, pred, pred_prob = row
    print(f"Target: {target}, Pred: {pred}, Prob: {pred_prob}")
    print(f"Text:\n{text}\n")
    print("----\n")

Target: 0, Pred: 1.0, Prob: 0.9058102965354919
Text:
? High Skies - Burning Buildings ? http://t.co/uVq41i3Kx2 #nowplaying

----

Target: 0, Pred: 1.0, Prob: 0.8841612935066223
Text:
FedEx will no longer transport bioterror pathogens in wake of anthrax lab mishaps http://t.co/lHpgxc4b8J

----

Target: 0, Pred: 1.0, Prob: 0.8419314622879028
Text:
@madonnamking RSPCA site multiple 7 story high rise buildings next to low density character residential in an area that floods

----

Target: 0, Pred: 1.0, Prob: 0.8405700922012329
Text:
@SonofLiberty357 all illuminated by the brightly burning buildings all around the town!

----

Target: 0, Pred: 1.0, Prob: 0.8317149877548218
Text:
@AshGhebranious civil rights continued in the 60s. And what about trans-generational trauma? if anything we should listen to the Americans.

----

Target: 0, Pred: 1.0, Prob: 0.8094304800033569
Text:
Ashes 2015: AustraliaÛªs collapse at Trent Bridge among worst in history: England bundled out Australia for 60 ... http://t.co/t5TrhjUAU0

----

Target: 0, Pred: 1.0, Prob: 0.7970582842826843
Text:
[55436] 1950 LIONEL TRAINS SMOKE LOCOMOTIVES WITH MAGNE-TRACTION INSTRUCTIONS http://t.co/xEZBs3sq0y http://t.co/C2x0QoKGlY

----

Target: 0, Pred: 1.0, Prob: 0.7691510915756226
Text:
FedEx no longer to transport bioterror germs in wake of anthrax lab mishaps http://t.co/qZQc8WWwcN via @usatoday

----

Target: 0, Pred: 1.0, Prob: 0.7666390538215637
Text:
My phone looks like it was in a car ship airplane accident. Terrible

----

Target: 0, Pred: 1.0, Prob: 0.7517023086547852
Text:
åÈMGN-AFRICAå¨ pin:263789F4 åÈ Correction: Tent Collapse Story: Correction: Tent Collapse story åÈ http://t.co/fDJUYvZMrv @wizkidayo

----

Target: 0, Pred: 1.0, Prob: 0.751211404800415
Text:
Deaths 3 http://t.co/nApviyGKYK

----

Target: 0, Pred: 1.0, Prob: 0.7478917241096497
Text:
@RebeccaforReal accepts Wisconsin Emergency Response Plan on behalf of @GovWalker #nbc15 http://t.co/Pis0aiVRbR

----

Target: 0, Pred: 1.0, Prob: 0.7416132688522339
Text:
The #tubestrike is because TFL workers may have trouble planning downtime. I hope none need emergency services. http://t.co/iCSFDSiFqb

----

Target: 0, Pred: 1.0, Prob: 0.7413390278816223
Text:
GENERAL AUDIENCE: On Wounded Families | ZENIT - The World Seen From Rome http://t.co/hFvnyfT78C

----

Target: 0, Pred: 1.0, Prob: 0.731740415096283
Text:
Air Group is here to the rescue! We have 24/7 Emergency Service! Learn more about it here - http://t.co/9lyx7zMtHE http://t.co/5PbC96rTMJ

----

Target: 0, Pred: 1.0, Prob: 0.7286658883094788
Text:
Do you have a plan? Emergency Preparedness for #Families of
Children with Special Needs  http://t.co/RdOVqaUAx5  #autism #specialneeds

----

Target: 0, Pred: 1.0, Prob: 0.723419189453125
Text:
A look at state actions a year after Ferguson's upheaval http://t.co/GZEkQWzijq

----

Target: 0, Pred: 1.0, Prob: 0.7229580879211426
Text:
The Sound of Arson

----

Target: 0, Pred: 1.0, Prob: 0.7171533107757568
Text:
@BrodyFrieling @hanna_brooksie photo bombed

----

Target: 0, Pred: 1.0, Prob: 0.705691933631897
Text:
@pxnatosil @RenuncieDilma  Fatality!

----

Target: 0, Pred: 1.0, Prob: 0.7032174468040466
Text:
@freefromwolves GodsLove &amp; #thankU brother Danny for RT of NEW VIDEO http://t.co/cybKsXHF7d The Coming Apocalyptic US Earthquake &amp; Tsunami

----

Target: 0, Pred: 1.0, Prob: 0.7019413113594055
Text:
@noah_anyname That's where the concentration camps and mass murder come in.

EVERY. FUCKING. TIME.

----

Target: 0, Pred: 1.0, Prob: 0.7000676989555359
Text:
Day 2. Liquidation of emergency at chemical object. #USAR2015 #USAR15 #RUOR #??????????? http://t.co/gGTmDqUdDo

----

Target: 0, Pred: 1.0, Prob: 0.6929640173912048
Text:
Trafford Centre film fans angry after Odeon cinema evacuated following false fire alarm   http://t.co/6GLDwx71DA

----

Target: 0, Pred: 1.0, Prob: 0.6773743033409119
Text:
Article by Michael Jackman at Metro Times Detroit:
The group later downgraded the estimate to 37 square miles of... http://t.co/h31mmuduqt

----

Target: 0, Pred: 1.0, Prob: 0.6686563491821289
Text:
Crack in the path where I wiped out this morning during beach run. Surface wounds on left elbow and right knee. http://t.co/yaqRSximph

----

Target: 0, Pred: 1.0, Prob: 0.6473670601844788
Text:
Photo: postapocalypticflimflam: Prodding around the rubble. http://t.co/Bgy4i47j70

----

Target: 0, Pred: 1.0, Prob: 0.641562283039093
Text:
@RedCoatJackpot *As it was typical for them their bullets collided and none managed to reach their targets; such was the ''curse'' of a --

----

Target: 0, Pred: 1.0, Prob: 0.6370474696159363
Text:
@cjbanning 4sake of argsuppose pre-born has attained individl rights.Generally courtof law forbids killing unless dead person did something

----

Target: 0, Pred: 1.0, Prob: 0.6350733041763306
Text:
Haley Lu Richardson Fights for Water in The Last Survivors (Review) http://t.co/oObSCFOKtQ

----

Target: 0, Pred: 1.0, Prob: 0.6343528628349304
Text:
Cyclists it is pandemonium on the roads today. Drive carefully!

----

Target: 0, Pred: 1.0, Prob: 0.6219336986541748
Text:
the windstorm blew thru my open window and now my bong is in pieces just another example of nature's indifference to human suffering

----

Target: 0, Pred: 1.0, Prob: 0.6193859577178955
Text:
Diageo's CEO stresses that a board revolt at United Spirits has not impacted Indian operations http://t.co/STPOdA901U

----

Target: 0, Pred: 1.0, Prob: 0.611751914024353
Text:
.@AIGinsurance CEO: Divestitures and #Catastrophe Losses Temper Q2 #Results http://t.co/2y2wZk1FrM

----

Target: 0, Pred: 1.0, Prob: 0.6071170568466187
Text:
#helpme what do I do? My friend has been ticketed by Police in Wayne County Michigan into never- sending poverty cycle. How do I help him?

----

Target: 0, Pred: 1.0, Prob: 0.5997627377510071
Text:
Love is the weapon for this wounded generation &lt;3

----

Target: 0, Pred: 1.0, Prob: 0.5727339386940002
Text:
Emergency Response and Hazardous Chemical Management: Principles and Practices http://t.co/4sSuyhkgRB http://t.co/TDerBtgZ2k

----

Target: 0, Pred: 1.0, Prob: 0.5705060958862305
Text:
there's this person &amp; they reckon when you're dying your brain floods with dmt causing you to relive your life in real time in a simulation

----

Target: 0, Pred: 1.0, Prob: 0.5679425597190857
Text:
Public Hearing on 2015-16 @SUNY_Orange budget Thurs 8/6 at 3:15 Emergency Services Ctr Goshen. http://t.co/80DzgCo6Vc

----

Target: 0, Pred: 1.0, Prob: 0.5464397072792053
Text:
@LegacyOfTheSith @SagaciousSaber @Lordofbetrayal Moved in a crescent formation small trails of dust left in their wake as they moved.

----

Target: 0, Pred: 1.0, Prob: 0.5421462655067444
Text:
@Azimel 'Screaming Mad Scientist deceased after tumbling over heels and falling into sinkhole during investigation'

----

Target: 0, Pred: 1.0, Prob: 0.540234386920929
Text:
Ignition Knock (Detonation) Sensor Connector-Connecto MOTORCRAFT WPT-410 http://t.co/bSmJ2HVgwD http://t.co/bXalnEdy49

----

Target: 0, Pred: 1.0, Prob: 0.5374796986579895
Text:
He made such a good point. White person comings mass murder labelled as criminal minority does the same thing... http://t.co/37qPsSnaCv

----

Target: 0, Pred: 1.0, Prob: 0.5271517038345337
Text:
WPRI 12 Eyewitness News Rhode Island set to modernize its voting equipment WPRI 12 EyewitnessÛ_ http://t.co/aP9JBrPmQg

----

Target: 0, Pred: 1.0, Prob: 0.5089625120162964
Text:
Came across this fire video not mine..enjoy..Babes way of saying hi to me while he's in the fire truck??
#fireman #Û_ http://t.co/V5gTUnwohy

----

Target: 0, Pred: 1.0, Prob: 0.5006320476531982
Text:
@nagel_ashley @Vicken52 @BasedLaRock @goonc1ty rip the world... its burning

----

Target: 1, Pred: 0.0, Prob: 0.499275267124176
Text:
For these Californians it's like living in Africa's Sahel desert - just finding water a daily chore. http://t.co/ySG9vsrT4g

----

Target: 1, Pred: 0.0, Prob: 0.49612751603126526
Text:
Tension In Bayelsa As Patience Jonathan Plans To Hijack APC PDP http://t.co/epABiNcZmJ http://t.co/1SgzGtgfw9

----

Target: 1, Pred: 0.0, Prob: 0.4871455430984497
Text:
Medieval airplane hijacker testa: earnings the distinction divers: HtaRvrGLY

----

Target: 1, Pred: 0.0, Prob: 0.48449641466140747
Text:
China's Stock Market Crash: Are There Gems In The Rubble? http://t.co/BqBLWiw08g #ROIMentor #yycwalks

----

Target: 1, Pred: 0.0, Prob: 0.47784900665283203
Text:
@Dirk_NoMissSki yea but if someone faints why are they panicking?.. thats basic stuff ??

----

Target: 1, Pred: 0.0, Prob: 0.4671921133995056
Text:
Back from Seattle Tacoma and Portland. Whirlwind! http://t.co/qwHINBni8e

----

Target: 1, Pred: 0.0, Prob: 0.4661847651004791
Text:
DireTube Information ÛÒ Egypt Cyprus and Greece agreed to fightåÊterrorism http://t.co/V6IjxCCD2I http://t.co/YSXhFWMGOD

----

Target: 1, Pred: 0.0, Prob: 0.4549778997898102
Text:
@canagal Good to hear it's back.. that storm's been given you guys trouble though :( ^SJ

----

Target: 1, Pred: 0.0, Prob: 0.4458657503128052
Text:
Nearly had a heart attack just now; loud bang against window next to meÛ_turns out it was two birds flying into the glass.

----

Target: 1, Pred: 0.0, Prob: 0.4396780729293823
Text:
133 N past  the 5 L lane is reopened. All other lanes are closed. All lanes are open on the 133 S. Trash truck fire cleanup. @KNX1070

----

Target: 1, Pred: 0.0, Prob: 0.43888747692108154
Text:
A Dayton-area org tells me it was hit by a cyber attack: http://t.co/7LhKJz0IVO

----

Target: 1, Pred: 0.0, Prob: 0.4188031554222107
Text:
I moved to England five years ago today. What a whirlwind of time it has been! http://t.co/eaSlGeA1B7

----

Target: 1, Pred: 0.0, Prob: 0.412870317697525
Text:
Oops: Bounty hunters try to raid Phoenix police chief's home: http://t.co/yPRJWMigHL -- A group of armed bounty... http://t.co/3RrKRCjYW7

----

Target: 1, Pred: 0.0, Prob: 0.41085511445999146
Text:
Hollywood Movie About Trapped Miners Released in Chile: 'The 33' Hollywood movie about trapped miners starring... http://t.co/tyyfG4qQvM

----

Target: 1, Pred: 0.0, Prob: 0.40590137243270874
Text:
When ur friend and u are talking about forest fires in a forest and he tells u to drop ur mix tape out there... #straightfire

----

Target: 1, Pred: 0.0, Prob: 0.40445661544799805
Text:
I never knew about the relationship btwn Kansas City Hyatt bridge collapse &amp; AIA's COTE.   http://t.co/ThS9IqSWP3 via @HuffPostArts

----

Target: 1, Pred: 0.0, Prob: 0.4002847969532013
Text:
@DavidJordan88 @Stephanenny Except we don't know who started the riot or if it even makes sense to credit any particular individuals...

----

Target: 1, Pred: 0.0, Prob: 0.3997142016887665
Text:
@KlaraJoelsson Well I have seen it now! That's a bummer. We've had this heat wave tho... 43'c!! I'd prefer the rain... :P

----

Target: 1, Pred: 0.0, Prob: 0.3977733850479126
Text:
#World #News Qld police wrap Billy Gordon investigation: QUEENSLAND Police have wrapped up their investigation...  http://t.co/msgnNDxOeK

----

Target: 1, Pred: 0.0, Prob: 0.3952868580818176
Text:
US wont upgrade its infrastructure? http://t.co/NGEHhG9YGa' it a bad situation and its going to get ugly very quickly #USA #sustainability

----

Target: 1, Pred: 0.0, Prob: 0.38401341438293457
Text:
@ColdMpress You up to commiting mass murder tonight?

----

Target: 1, Pred: 0.0, Prob: 0.3722507059574127
Text:
Breakfast links: Work from home: Derailed: An empty train derailed at Smithsonian this morning suspending ser... http://t.co/iD4QGqDnJQ

----

Target: 1, Pred: 0.0, Prob: 0.37156036496162415
Text:
RT NotExplained: The only known image of infamous hijacker D.B. Cooper. http://t.co/JlzK2HdeTG

----

Target: 1, Pred: 0.0, Prob: 0.36685994267463684
Text:
Toddler drowned in bath after mum left room to fetch his pyjamas http://t.co/k9aSKtwXfL

----

Target: 1, Pred: 0.0, Prob: 0.35944539308547974
Text:
#Metepec #Mexico - ?NIGHT DISASTER?...E(Oficial) @ #NitClub #mÌ¼sica #mÌ¼sica http://t.co/WTfJF9jjzs

----

Target: 1, Pred: 0.0, Prob: 0.35855862498283386
Text:
@emmerdale can we have a public vote for the next annual village disaster?  i want an isis strike or a nuclear accident &amp; end this forever

----

Target: 1, Pred: 0.0, Prob: 0.349984347820282
Text:
Policyholders object to Clico rescue plan http://t.co/E4DvI9vUXZ http://t.co/JyCpf8iYhg

----

Target: 1, Pred: 0.0, Prob: 0.34963443875312805
Text:
#ClimateChange Eyewitness to Extreme Weather: 11 Social Media Posts that Show Just How Crazy Things A... http://t.co/czpDn9oBiT #Anarchy

----

Target: 1, Pred: 0.0, Prob: 0.34498757123947144
Text:
Savings and sewing in Guatemala: Savings and sewing in Guatemala. When a natural disaster hit seamstress Elvia...  http://t.co/jdx9OX2kIk

----

Target: 1, Pred: 0.0, Prob: 0.3367587924003601
Text:
There's a weird siren going off here...I hope Hunterston isn't in the process of blowing itself to smithereens...

----

Target: 1, Pred: 0.0, Prob: 0.335860013961792
Text:
Crazy Mom Threw Teen Daughter a NUDE Twister Sex Party According To Her Friend50 =&gt;http://t.co/Hy5Pbe12TM http://t.co/c1nJpLi5oR

----

Target: 1, Pred: 0.0, Prob: 0.3159950375556946
Text:
So this storm just came out of no where. .fuck me its cool

----

Target: 1, Pred: 0.0, Prob: 0.29967284202575684
Text:
How is it one careless match can start a forest fire but it takes a whole box to start a campfire?

----

Target: 1, Pred: 0.0, Prob: 0.28263071179389954
Text:
shit is hard to get over but sometimes the tragedy means it's over soulja..

----

Target: 1, Pred: 0.0, Prob: 0.2751544117927551
Text:
Another fake hate crime Lesbians burn their own house down. What else Is new :http://t.co/66oBQmxImb

----

Target: 1, Pred: 0.0, Prob: 0.2574392259120941
Text:
In Kalmikya Astrakhan Volgagrad and Dagestan there is already no food left for the locusts

  http://t.co/79Fw9zWxtP via @TIMEWorld

----

Target: 1, Pred: 0.0, Prob: 0.257304310798645
Text:
Owner of Chicago-Area Gay Bar Admits to Arson Scheme http://t.co/ZPxE3fMYNG #LGBT

----

Target: 1, Pred: 0.0, Prob: 0.25137293338775635
Text:
Would a paramedic really do that? Leave someone inside a building that's about to collapse/blow up? @HalloIkBenWill

----

Target: 1, Pred: 0.0, Prob: 0.23324158787727356
Text:
when you don't know which way an ambulance is coming from &lt;&lt;

----

Target: 1, Pred: 0.0, Prob: 0.22873350977897644
Text:
First time getting into #gbbo2015 and physically gasped at the cake 'mudslide' incident already way too emotionally invested...

----

Target: 1, Pred: 0.0, Prob: 0.21468785405158997
Text:
The date for the release of EP03 DESOLATION is set. Stay tuned for more info while we finalise the schedule. #alt #electro #rock #comingsoon

----

Target: 1, Pred: 0.0, Prob: 0.21299181878566742
Text:
#hot  Funtenna: hijacking computers to send data as sound waves [Black Hat 2015] http://t.co/cOMuiOk3mP #prebreak #best

----

Target: 1, Pred: 0.0, Prob: 0.20053811371326447
Text:
CDC has a pretty cool list of all bioterrorism agents :3

----

Target: 1, Pred: 0.0, Prob: 0.196767196059227
Text:
Stupid women nearly collided into me today after she came out of a junction not looking. Still kept coming towards me till I beep my horn

----

Target: 1, Pred: 0.0, Prob: 0.19513154029846191
Text:
@camilacabello97 Internally and externally screaming

----

Target: 1, Pred: 0.0, Prob: 0.19478698074817657
Text:
Sadly before she could save humanity Ursula drowned in the drool of a protoshoggoth but at least she sort of died doing what she loved.

----

Target: 1, Pred: 0.0, Prob: 0.19405166804790497
Text:
Plans by former First Lady and wife of ex-President Goodluck Jonathan Dame Patience Jonathan to hijack the All... http://t.co/HaShGQAFic

----

Target: 1, Pred: 0.0, Prob: 0.1820337176322937
Text:
Indeed!! I am fully aware of that battle! I support you in that fight!!  https://t.co/MctJnZX4H8

----

Target: 1, Pred: 0.0, Prob: 0.17847225069999695
Text:
Can't believe more people in their mid 20's don't have high blood pressure. Life is stressful. #DecisionsOnDecisions

----

Target: 1, Pred: 0.0, Prob: 0.17707504332065582
Text:
Julian Knight - @SCVSupremeCourt dismisses mass murderer's attempt to increase prisoner pay. Challenged quantum of 5% increase 2013.

----

Target: 1, Pred: 0.0, Prob: 0.1766599863767624
Text:
#download &amp; #watch Demolition Frog (2002) http://t.co/81nEizeknm #movie

----

Target: 1, Pred: 0.0, Prob: 0.17544777691364288
Text:
When you go to a concert and someone screams in your ear... Does it look like I wanna loose my hearing anytime soon???

----

Target: 1, Pred: 0.0, Prob: 0.17435550689697266
Text:
Two hours to get to a client meeting. Whirlwind of emotions with this #tubestrike

----

Target: 1, Pred: 0.0, Prob: 0.16799966990947723
Text:
@dreamoforgonon @TeeEss not to hijack but as a bona fide cislady I can confirm this as true; incidental homosexuality =/= gay/bi for women.

----

Target: 1, Pred: 0.0, Prob: 0.15762299299240112
Text:
Body shops inundated with cars dented by hail... Good news insurance pays... Bad news :  you are stuck with deductible !
#wcvb

----

Target: 1, Pred: 0.0, Prob: 0.15198957920074463
Text:
@MichaelWestBiz standard damage control

----

Target: 1, Pred: 0.0, Prob: 0.14371460676193237
Text:
suddenly it's off &amp; on gloomy &amp; thunder so loud it shakes the windows? Not ever on the Bay Area. Miss me w/that lol http://t.co/x4eCGGvnSN

----

Target: 1, Pred: 0.0, Prob: 0.1431424766778946
Text:
World War II book LIGHTNING JOE An Autobiography by General J. Lawton Collins http://t.co/R4khEH7iaf http://t.co/qSZgJfUutu

----

Target: 1, Pred: 0.0, Prob: 0.14181950688362122
Text:
How to prepare your #property for a #storm:

http://t.co/KhYqQsi6My http://t.co/G6Vs3XEinb

----

Target: 1, Pred: 0.0, Prob: 0.14009727537631989
Text:
So I pick myself off the ground and swam before I drowned. Hit the bottom so hard I bounced twice suffice this time around is different.

----

Target: 1, Pred: 0.0, Prob: 0.1381615400314331
Text:
Just came back from camping and returned with a new song which gets recorded tomorrow. Can't wait! #Desolation #TheConspiracyTheory #NewEP

----

Target: 1, Pred: 0.0, Prob: 0.12729065120220184
Text:
@Habbo bring back games from the past. Snowstorm. Tic tac toe. Battleships. Fast food. Matchwood.

----

Target: 1, Pred: 0.0, Prob: 0.12564660608768463
Text:
annihilating quarterstaff of annihilation

----

Target: 1, Pred: 0.0, Prob: 0.12455534189939499
Text:
Yelp Bolsters Health Care Reviews With Investigative Journalism: Sick and injured patients at a local ER are t... http://t.co/E8aEGOFDY2

----

Target: 1, Pred: 0.0, Prob: 0.11963331699371338
Text:
A quarter whirlwind. They don't see it coming.

----

Target: 1, Pred: 0.0, Prob: 0.11244044452905655
Text:
@SaintRobinho86 someone has to be at the bottom of every league. Tonight clearly demonstrated why the Lions are where they are - sunk!

----

Target: 1, Pred: 0.0, Prob: 0.1048579290509224
Text:
Until my death I'll forever rep the Jets.

----

Target: 1, Pred: 0.0, Prob: 0.10455698519945145
Text:
I wanna set some shit on fire.

----

Target: 1, Pred: 0.0, Prob: 0.10386117547750473
Text:
@cspanwj If 90BLKs&amp;8WHTs colluded 2 take WHT F @USAgov AUTH Hostage&amp;2 make her look BLK w/Bioterrorism&amp;use her lgl/org IDis ID still hers?

----

Target: 1, Pred: 0.0, Prob: 0.0968569740653038
Text:
Rand Paul's Debate Strategy 'demolish Some other bad ideas out there or point out maybe that there are some em... http://t.co/qzdqRBr4Lh

----

Target: 1, Pred: 0.0, Prob: 0.09427900612354279
Text:
The ol' meltdown victory for the Mets.

----

Target: 1, Pred: 0.0, Prob: 0.09422652423381805
Text:
@Zak_Bagans this is Sabrina my dad rescued her from some dude who kept her in a cage. We've had her since I was 4 http://t.co/1k2PhQcuW8

----

Target: 1, Pred: 0.0, Prob: 0.09341061860322952
Text:
@GodOf_Mischief_ -of Loki's daggers she pulled it out and jammed it into Mina's thigh. When Mina screamed and grabbed at her leg sif-


In [104]:
test_data

,id,keyword,location,text
0,0,NaN,NaN,Just happened a terrible car crash
1,2,NaN,NaN,"Heard about #earthquake is different cities, s..."
2,3,NaN,NaN,"there is a forest fire at spot pond, geese are..."
3,9,NaN,NaN,Apocalypse lighting. #Spokane #wildfires
4,11,NaN,NaN,Typhoon Soudelor kills 28 in China and Taiwan
...,...,...,...,...
3258,10861,NaN,NaN,EARTHQUAKE SAFETY LOS ANGELES ÛÒ SAFETY FASTE...
3259,10865,NaN,NaN,Storm in RI worse than last hurricane. My city...
3260,10868,NaN,NaN,Green Line derailment in Chicago http://t.co/U...
3261,10874,NaN,NaN,MEG issues Hazardous Weather Outlook (HWO) htt...
3262,10875,NaN,NaN,#CityofCalgary has activated its Municipal Eme...

### Making predicitons on the test dataset

In [105]:
# Making predictions on the test dataset and visualizing them
test_sentences = test_data["text"].to_list()
test_samples = random.sample(test_sentences, 10)
for test_sample in test_samples:
    pred_prob = tf.squeeze(loaded_model_6_savedModel_format.predict([test_sample])) # our model expects a list as input
    pred = tf.round(pred_prob)
    print(f"Pred: {int(pred)}, Prob: {pred_prob}")
    print(f"Text:\n{test_sample}\n")
    print("----\n")

1/1 [==============================] - 1s 513ms/step
Pred: 1, Prob: 0.7126947045326233
Text:
http://t.co/OK9EBHurfl If your neighborhood school falls into a sinkhole State Sen. Steve Yarbrough may be close by...

----

1/1 [==============================] - 0s 45ms/step
Pred: 1, Prob: 0.8737825751304626
Text:
KCEM Jeff King reports a level 3 evacuation east of Roosevelt from Whitner rd to the county line between SR14 &amp; Hale rd.

----

1/1 [==============================] - 0s 49ms/step
Pred: 0, Prob: 0.18552625179290771
Text:
The balloon thing was so rude I would have popped the balloon than whoever blew it up's face

----

1/1 [==============================] - 0s 46ms/step
Pred: 1, Prob: 0.8948627710342407
Text:
Severe Thunderstorm Warning until 08:00 PM local for Custer Fall River &amp; Shannon Counties in SD. 60 Mph Wind Gusts And Penny Size Hail. #sd

----

1/1 [==============================] - 0s 46ms/step
Pred: 0, Prob: 0.14314763247966766
Text:
@thomasa56 Just ONE of my major reasons not to live in *Big City*. If RR's *miss 9 meals* ever comes to pass Cue ANY 'Apocalypse' script.

----

1/1 [==============================] - 0s 45ms/step
Pred: 1, Prob: 0.9906608462333679
Text:
Remembering Sgt.-Maj. Roni Ghanem 28 of Maghar murdered by Hamas terrorists in the suicide bombing of Egged bus No. 361 13 years ago today

----

1/1 [==============================] - 0s 46ms/step
Pred: 1, Prob: 0.9889213442802429
Text:
Landslide in Italian Alps kills three: ROME (Reuters) - Three people were killed when a severe rainstorm in th... http://t.co/mBPWr0fUvJ

----

1/1 [==============================] - 0s 46ms/step
Pred: 0, Prob: 0.07630372047424316
Text:
@itsTiimothy bhill bruh you can obliterate beez

----

1/1 [==============================] - 0s 45ms/step
Pred: 0, Prob: 0.3702956736087799
Text:
?????? EMERGENCY ?????? NEED PART 2 and 3!!! #NashNewVideo http://t.co/TwdnNaIOns @Nashgrier 103

----

1/1 [==============================] - 0s 47ms/step
Pred: 0, Prob: 0.43947792053222656
Text:
#360WiseNews : China's Stock Market Crash: Are There Gems In The Rubble? http://t.co/vTJ1EoslrU

----

## The speed/score tradeoff

In [115]:
# Let's make a function to measure the time of prediction
import time
def pred_timer(model, samples):
    """
    Times how long a model takes to make predictions on samples.
    """
    start_time = time.perf_counter() # get start time
    model.predict(samples) # make predictions
    end_time = time.perf_counter() # get finish time
    total_time = end_time-start_time # calculate how long predictions took to make
    time_per_pred = total_time/len(samples)
    return total_time, time_per_pred

In [116]:
# Calculate TF Hub sentence encoder time per pred
model_6_total_pred_time, model_6_time_per_pred = pred_timer(model=loaded_model_6_savedModel_format,
                                                            samples=val_sentences)
model_6_total_pred_time, model_6_time_per_pred

24/24 [==============================] - 0s 12ms/step

(0.5074298000035924, 0.0006659183727081264)

In [117]:
# Calculate our baseline model times per pred
baseline_total_pred_time, baseline_time_per_pred = pred_timer(model_0, val_sentences)
baseline_total_pred_time, baseline_time_per_pred

(0.07817870000144467, 0.00010259671916200087)