In [1]:
# Import series of helper function for the notebook
from Helper_functions import create_tensorboard_callback, plot_loss_curves, compare_historys

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

## Get a text dataset

The dataset we're going to be using is Kaggle's introduction to NLP dataset (text samples of Tweets labelled as disaster or not disaster)

In [2]:
import pandas as pd

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')

train_data.head()

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

In [3]:
train_data['text'][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

In [4]:
# Shuffle training dataframe
train_data_shuffled = train_data.sample(frac=1, random_state=42)
train_data_shuffled

,id,keyword,location,text,target
2644,3796,destruction,NaN,So you have a new weapon that can cause un-ima...,1
2227,3185,deluge,NaN,The f$&amp;@ing things I do for #GISHWHES Just...,0
5448,7769,police,UK,DT @georgegalloway: RT @Galloway4Mayor: ÛÏThe...,1
132,191,aftershock,NaN,Aftershock back to school kick off was great. ...,0
6845,9810,trauma,"Montgomery County, MD",in response to trauma Children of Addicts deve...,0
...,...,...,...,...,...
5226,7470,obliteration,Merica!,@Eganator2000 There aren't many Obliteration s...,0
5390,7691,panic,NaN,just had a panic attack bc I don't have enough...,0
860,1242,blood,NaN,Omron HEM-712C Automatic Blood Pressure Monito...,0
7603,10862,NaN,NaN,Officials say a quarantine is in place at an A...,1
7270,10409,whirlwind,Stamford & Cork (& Shropshire),I moved to England five years ago today. What ...,1

In [5]:
# Test data
test_data.head()

   id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [6]:
# Count of samples
train_data.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [7]:
# Let's visualize some random training examples
import random 
random_index = random.randint(0, len(train_data)-5) # Create random indexes
for row in train_data_shuffled[["text", "target"]][random_index:random_index+5].itertuples():
    _, text, target = row
    print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
    print(f"Text:\n{text}\n")
    print("---\n")

Target: 1 (real disaster)
Text:
@DalaiLama then have the biggest nuclear disaster to ever have happened

---

Target: 0 (not real disaster)
Text:
Fire hazard associated with installation of non-compliant external cladding on high-rise buildings - Insurance - Aust http://t.co/wFsEaOBATo

---

Target: 1 (real disaster)
Text:
VIDEO: 'We're picking up bodies from water': Rescuers are searching for hundreds of migrants in the Mediterran... http://t.co/GEU4H46CsZ

---

Target: 0 (not real disaster)
Text:
@hoodedu You fucking better Berlatsky.  If I don't win this fucking thing in a landslide I'm holding you personally fucking responsible.

---

Target: 1 (real disaster)
Text:
On anniversary of Hiroshima bombing illustrated timeline of bombings. Eyewitness account particularly horrifying http://t.co/GZIb0mAwmn

---

### Split data into training and validation sets
Since the test set has no labels and we need a way to evaluate our trained models, we'll split off some of the trianing data and create validation set.

In [8]:
from sklearn.model_selection import train_test_split

train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_data_shuffled["text"].to_numpy(),
                                                                            train_data_shuffled["target"].to_numpy(),
                                                                            test_size=0.1,
                                                                            random_state=42)

In [9]:
# checking the length
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [10]:
# first 10 training sentences and their labels
train_sentences[:10], train_labels

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0, 0, 1, ..., 1, 1, 0], dtype=int64))

## Converting text into numbers

There are two main techniques to convert text into numbers:

1. Text tokenization
2. Text embeddings

### Text tokenization

In [11]:
import tensorflow as tf 
from tensorflow.keras.layers import TextVectorization

text_vectorizer = TextVectorization(max_tokens=None, # how many words in the vocabulary (all of the different words in text)
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None,
                                    output_mode="int",
                                    output_sequence_length=None)

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [12]:
# Find average number of tokens (words) in training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [13]:
# Setup text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 15

text_vectorizer = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [14]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences)

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

In [15]:
# Create a sample sentence and tokenize it 
sample_sentence = "There's a flood in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]], dtype=int64)>

In [16]:
# Choose a random sentence from the training dataset and tokenize it
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
    \n\nVectorized version:")
text_vectorizer([random_sentence])

Original text:
 @deniseromano @megynkelly @GOP That's one way to make their heads explode...

Vectorized version:

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[   1, 5142, 1016,  215,   61,  147,    5,  144,  131, 2096,  332,
           0,    0,    0,    0]], dtype=int64)>

In [17]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectorizer.get_vocabulary() # Get all of the unique words in our training data
top_5_words = words_in_vocab[:5] # get the most common words
bottom_5_words = words_in_vocab[-5:] # get the least common words
print(f"Number of words in vocab: {len(words_in_vocab)}")
print(f"5 most common words: {top_5_words}")
print(f"5 least common words: {bottom_5_words}")

Number of words in vocab: 10000
5 most common words: ['', '[UNK]', 'the', 'a', 'in']
5 least common words: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']

## Creating an Embedding using an Embedding Layer

The parameters we care most about for our embedding layer:
* `input_dim` = the size of our vocabulary
* `output_dim` = the size of the output embedding vector, for example, a value of 100 would mean each token gets represented by a vector 100 long
* `input_length` = length of the sequences being passed to the embedding layer

In [18]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128,
                             input_length=max_length # how long is each input
                             )
embedding

In [19]:
# Get a random sentence from the training set
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
    \n\nEmbedded version:")

# Embed the random sentence (turn it into dense vectors of fixed size)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
 hurricane?? sick!

Embedded version:

<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.01292863, -0.03077503,  0.0038232 , ..., -0.00754821,
          0.00572913,  0.0012063 ],
        [ 0.02399609,  0.0073411 ,  0.01932976, ..., -0.00486869,
          0.03275261, -0.00116649],
        [-0.02069898,  0.01339087,  0.03880003, ..., -0.01287209,
          0.02445154, -0.0024901 ],
        ...,
        [-0.02069898,  0.01339087,  0.03880003, ..., -0.01287209,
          0.02445154, -0.0024901 ],
        [-0.02069898,  0.01339087,  0.03880003, ..., -0.01287209,
          0.02445154, -0.0024901 ],
        [-0.02069898,  0.01339087,  0.03880003, ..., -0.01287209,
          0.02445154, -0.0024901 ]]], dtype=float32)>

In [20]:
# Check out a single token's embdedding
sample_embed[0][0], sample_embed[0][0].shape, random_sentence

(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.01292863, -0.03077503,  0.0038232 ,  0.02916194, -0.01986692,
         0.02744441,  0.00043967, -0.00567608, -0.01846058,  0.04608997,
        -0.04028568, -0.03691292,  0.03993933,  0.02681712, -0.01010006,
         0.01733461, -0.0458699 ,  0.03235033, -0.0158255 , -0.04888409,
         0.03140232,  0.03138382, -0.02932415, -0.01036477,  0.01257372,
         0.01734115,  0.00251257, -0.00604554, -0.02838935,  0.02138335,
        -0.00165772, -0.02174748, -0.02610688, -0.01336821, -0.02254556,
        -0.00779575, -0.00247325, -0.02990812, -0.00769036, -0.01410545,
        -0.00648503, -0.00395418, -0.00375427, -0.04584071, -0.0077039 ,
         0.03364631,  0.00658175,  0.02595748, -0.01228087, -0.01798654,
        -0.02755082, -0.01166844, -0.04122573,  0.0393048 ,  0.0337805 ,
        -0.03621244, -0.0420486 ,  0.02081022,  0.01653377,  0.03000176,
         0.02578247,  0.01879572, -0.01741915,  0.02492576, -0.00696731,
         0.02329906,  0.00544289, -0.03873298,  0.02183456, -0.02157022,
         0.01289317, -0.01811304,  0.02708819,  0.02030936, -0.03741698,
         0.00489493,  0.01497997, -0.04362462,  0.00623978,  0.04102479,
        -0.02710111, -0.04177012,  0.04982233,  0.02748222,  0.03094238,
        -0.03309254, -0.00534594,  0.02220858, -0.02892914, -0.04258871,
         0.03180021,  0.00670631,  0.04782969, -0.02671663, -0.03512732,
         0.01504767,  0.04368706, -0.00186495, -0.01247336, -0.02445316,
        -0.03513686,  0.03372763, -0.0198912 ,  0.01292593,  0.0213125 ,
         0.03370771,  0.04911925,  0.01082568,  0.03503814,  0.00700474,
         0.04763291, -0.00366135, -0.02849532,  0.03818575, -0.01470778,
         0.03986004, -0.00026114, -0.04145944, -0.03757086,  0.04775823,
        -0.024497  , -0.01102418, -0.00565978,  0.04256046,  0.01535434,
        -0.00754821,  0.00572913,  0.0012063 ], dtype=float32)>,
 TensorShape([128]),
 'hurricane?? sick!')

## Modelling a text dataset (running a series of experiments)

Now we've a got way to turn our text sequences into numbers, it's time to start building a series of modelling experiments.

We'll start with a baseline and move on from there

* Model 0: Naive Bayes (baseline).
* Model 1: Feed-Forward neural network (dense model)
* Model 2: LSTM model (RNN)
* Model 3: GRU model (RNN)\
* Model 4: Bidirectional-LSTM model (RNN)
* Model 5: 1D Convolutional Neural Network (CNN)
* Model 6: TensorFlow Hub pretrained feature extractor (using transfer learning for NLP)
* Model 7: Same as model 6 with 10% of training data.

### Model 0: Getting a baseline

As with all machine learning modelling experiments, it's important to create as baseline model so you have got a benchmark for future experiments to build upon.

To create our baseline, we'll use sklearn's multinomial naive bayes using the TF-IDF formula to convert our words to numbers.

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline

# Create tokenization and modelling pipeline
model_0 = Pipeline([
    ("tfidf", TfidfVectorizer()), # convert words to numbers 
    ("clf", MultinomialNB()) # model the text
])

# Fit the pipeline to the training data
model_0.fit(train_sentences, train_labels)

Pipeline(steps=[('tfidf', TfidfVectorizer()), ('clf', MultinomialNB())])

In [22]:
# Evaluate our baseline model
baseline_score = model_0.score(val_sentences, val_labels)
print(f"Our baseline model achieves an accuracy of: {baseline_score*100:.2f}%")

Our baseline model achieves an accuracy of: 79.27%

In [23]:
# Make predictions 
baseline_preds = model_0.predict(val_sentences)
baseline_preds[:20]

array([1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1],
      dtype=int64)

### Creating an evaluation function for our model experiments

In [24]:
# Function to evaluate: accuracy, precision, recall and f1-score
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def calculate_results(y_true, y_pred):
    """
    Calculates model accuracy, precision, recall and f1 score of a binary classification model.

    """
    # Calculate model accuracy 
    model_accuracy = accuracy_score(y_true, y_pred) * 100
    # Calculate model precision , recall and f1-score using "weighted" average
    model_precision, model_recall, model_f1, _ = precision_recall_fscore_support(y_true, y_pred, average="weighted")
    model_results = {"accuracy": model_accuracy,
                     "precision": model_precision,
                     "recall": model_recall,
                     "f1": model_f1}
    return model_results

In [25]:
# Get baseline result
baseline_results = calculate_results(y_true=val_labels,
                                     y_pred=baseline_preds)
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

### Model 1: A simple dense model

In [26]:
# BUild model with the Funcitonal API
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string) # inputs are 1-dimensional strings
x = text_vectorizer(inputs) # turn the input text into numbers
x = embedding(x) # embedding of the numberized inputs
x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x) # output layers 
model_1 = tf.keras.Model(inputs, outputs, name="model_1_dense")

In [27]:
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 global_average_pooling1d (  (None, 128)               0
 GlobalAveragePooling1D)

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (4.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [28]:
# Compile model
model_1.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [29]:
val_sentences.shape, val_labels.shape

((762,), (762,))

In [30]:
# fit the model
model_1_history = model_1.fit(x=train_sentences,
                              y=train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

215/215 [==============================] - 5s 20ms/step - loss: 0.6117 - accuracy: 0.6998 - val_loss: 0.5349 - val_accuracy: 0.7585
Epoch 2/5
215/215 [==============================] - 4s 19ms/step - loss: 0.4406 - accuracy: 0.8161 - val_loss: 0.4693 - val_accuracy: 0.7861
Epoch 3/5
215/215 [==============================] - 4s 19ms/step - loss: 0.3463 - accuracy: 0.8608 - val_loss: 0.4608 - val_accuracy: 0.7861
Epoch 4/5
215/215 [==============================] - 4s 21ms/step - loss: 0.2842 - accuracy: 0.8946 - val_loss: 0.4629 - val_accuracy: 0.7861
Epoch 5/5
215/215 [==============================] - 4s 19ms/step - loss: 0.2379 - accuracy: 0.9114 - val_loss: 0.4822 - val_accuracy: 0.7900

In [31]:
# Check the results
model_1.evaluate(val_sentences, val_labels)

24/24 [==============================] - 0s 2ms/step - loss: 0.4822 - accuracy: 0.7900

[0.48219209909439087, 0.7900262475013733]

In [32]:
# Make some predictions and evalutate those
model_1_pred_probs = model_1.predict(val_sentences)
model_1_pred_probs.shape

24/24 [==============================] - 0s 1ms/step

(762, 1)

In [33]:
model_1_pred_probs[0]

array([0.3230018], dtype=float32)

In [34]:
# Convert model prediciton probabilities  to label format
model_1_preds = tf.squeeze(tf.round(model_1_pred_probs))
model_1_preds[:20]

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0.], dtype=float32)>

In [35]:
# Calculate our model_1 results
model_1_results = calculate_results(y_true=val_labels,
                                    y_pred=model_1_preds)
model_1_results

{'accuracy': 79.00262467191601,
 'precision': 0.7964718621790533,
 'recall': 0.7900262467191601,
 'f1': 0.7866259949990327}

## Visualizing learned mebeddings

In [36]:
# Get the vocabulary from the text vectorization layer
words_in_vocab = text_vectorizer.get_vocabulary()
len(words_in_vocab), words_in_vocab[:10]

(10000, ['', '[UNK]', 'the', 'a', 'in', 'to', 'of', 'and', 'i', 'is'])

In [37]:
# model 1 summary
model_1.summary()

Model: "model_1_dense"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 global_average_pooling1d (  (None, 128)               0
 GlobalAveragePooling1D)

 dense (Dense)               (None, 1)                 129

=================================================================
Total params: 1280129 (4.88 MB)
Trainable params: 1280129 (4.88 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [38]:
# Get tghe weight matrix of embedding layer
# (these are the numerical representations of each token in our training, which have been learned for ~5 epochs)
embed_weights = model_1.get_layer("embedding").get_weights()[0]
embed_weights.shape

(10000, 128)

In [39]:
# Create mebedding files (we got this from TensorFlow's word embedding documnetation)
import io
out_v = io.open('vectors.tsv', 'w', encoding='utf-8')
out_m = io.open('metadata.tsv', 'w', encoding='utf-8')

for index, word in enumerate(words_in_vocab):
    if index == 0:
        continue # Skip 0, it's padding.
    vec = embed_weights[index]
    out_v.write('\t'.join([str(x) for x in vec]) + "\n")
    out_m.write(word + "\n")
out_v.close()
out_m.close()

## Recurrent Neural Networks (RNN's)

RNN's are useful for sequential data.

The premise of a recurrent neural network is to use the representation of a previous input to aid the representation of a later input.

### Model 2: LSTM

Our structure of an RNN typically looks like this:

```
Input (txt) -> Tokenize -> Embedding -> Layers (RNNs/Dense) -> Output (label probability)
```

In [40]:
# Create an LSTM model
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
# print(x.shape)
x = layers.LSTM(64, return_sequences=True)(x) # when you're stacking RNN cells together , you need to set return_sequences=True
# print(x.shape)
x = layers.LSTM(64)(x)
# print(x.shape)
# x = layers.Dense(64, activation="relu")(x)
# print(x.shape)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_2 = tf.keras.Model(inputs, outputs, name="model_2_LSTM")

In [41]:
# Get a summary()
model_2.summary()

Model: "model_2_LSTM"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_2 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 lstm (LSTM)                 (None, 15, 64)            49408

 lstm_1 (LSTM)               (None, 64)                33024

 dense_1 (Dense)             (None, 1)                 65

=================================================================
Total params: 1362497 (5.20 MB)
Trainable params: 1362497 (5.20 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [42]:
# Compile the model
model_2.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [43]:
# Fit the model
model_2.history = model_2.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 11s 33ms/step - loss: 0.2265 - accuracy: 0.9191 - val_loss: 0.6661 - val_accuracy: 0.7743
Epoch 2/5
215/215 [==============================] - 6s 27ms/step - loss: 0.1578 - accuracy: 0.9431 - val_loss: 0.5565 - val_accuracy: 0.7861
Epoch 3/5
215/215 [==============================] - 5s 25ms/step - loss: 0.1304 - accuracy: 0.9533 - val_loss: 0.7333 - val_accuracy: 0.7756
Epoch 4/5
215/215 [==============================] - 6s 29ms/step - loss: 0.1060 - accuracy: 0.9612 - val_loss: 0.8004 - val_accuracy: 0.7703
Epoch 5/5
215/215 [==============================] - 5s 25ms/step - loss: 0.0830 - accuracy: 0.9683 - val_loss: 1.0313 - val_accuracy: 0.7730

In [44]:
# Make predictions with LSTM model
model_2_pred_probs = model_2.predict(val_sentences)
model_2_pred_probs[:10]

24/24 [==============================] - 1s 6ms/step

array([[2.4333796e-03],
       [6.0004628e-01],
       [9.9993378e-01],
       [5.4434627e-02],
       [3.8433148e-04],
       [9.9969423e-01],
       [9.8139125e-01],
       [9.9993449e-01],
       [9.9991608e-01],
       [4.0510491e-01]], dtype=float32)

In [45]:
# Convert model 2 pred probs to labels
model_2_preds = tf.squeeze(tf.round(model_2_pred_probs))
model_2_preds[:10]

In [46]:
# Calculate model 2 results
model_2_results = calculate_results(y_true=val_labels,
                                    y_pred=model_2_preds)
model_2_results

{'accuracy': 77.29658792650919,
 'precision': 0.7745161732477092,
 'recall': 0.7729658792650919,
 'f1': 0.7709704727215051}

In [47]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

### Model 3: GRU

Another popular and effective RNN component is the GRU or gated recurrent unit.
The GRU cell has similar features to an LSTM cell but but has less parameters.

In [48]:
# Buld an RNN using the GRU cell
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.GRU(64)(x)
# x = layers.GRU(64, return_sequences=True)(x)
# x = layers.LSTM(64, return_sequences=True)(x)
# x = layers.GRU(64, return_sequences=True)(x)
# x = layers.Dense(64, activation="relu")(x)
# x = layers.GlobalAveragePooling1D()(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_3 = tf.keras.Model(inputs, outputs, name="model_3_GRU")

In [49]:
model_3.summary()

Model: "model_3_GRU"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 gru (GRU)                   (None, 64)                37248

 dense_2 (Dense)             (None, 1)                 65

=================================================================
Total params: 1317313 (5.03 MB)
Trainable params: 1317313 (5.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [50]:
# Compile the model
model_3.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [51]:
# Fit the model
model_3_history = model_3.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 8s 25ms/step - loss: 0.1636 - accuracy: 0.9340 - val_loss: 0.6770 - val_accuracy: 0.7795
Epoch 2/5
215/215 [==============================] - 5s 22ms/step - loss: 0.0836 - accuracy: 0.9686 - val_loss: 0.7464 - val_accuracy: 0.7795
Epoch 3/5
215/215 [==============================] - 5s 22ms/step - loss: 0.0718 - accuracy: 0.9729 - val_loss: 0.8599 - val_accuracy: 0.7782
Epoch 4/5
215/215 [==============================] - 5s 22ms/step - loss: 0.0601 - accuracy: 0.9758 - val_loss: 1.0491 - val_accuracy: 0.7743
Epoch 5/5
215/215 [==============================] - 5s 25ms/step - loss: 0.0524 - accuracy: 0.9777 - val_loss: 1.0936 - val_accuracy: 0.7638

In [52]:
# Make some predictions with our GRU model
model_3_pred_probs = model_3.predict(val_sentences)
model_3_pred_probs[:10]

24/24 [==============================] - 1s 3ms/step

array([[2.0513115e-02],
       [9.0289766e-01],
       [9.9992663e-01],
       [9.5430486e-02],
       [3.4789133e-04],
       [9.9988514e-01],
       [9.9179101e-01],
       [9.9996215e-01],
       [9.9993837e-01],
       [9.7469419e-01]], dtype=float32)

In [53]:
# Convert model 3 pred probs to labels
model_3_preds = tf.squeeze(tf.round(model_3_pred_probs))
model_3_preds[:10]

In [54]:
# calculate model 3 results
model_3_results = calculate_results(y_true=val_labels,
                                    y_pred=model_3_preds)
model_3_results

{'accuracy': 76.37795275590551,
 'precision': 0.7634625473878772,
 'recall': 0.7637795275590551,
 'f1': 0.7635363942142148}

### Model 4: Bidirectional RNN
Normal RNN's go from left to right (just like you'd read an English sentence) however, a bidirectional RNN goes left to right also.

In [55]:
# Build a bidirectional RNN in TensorFlow
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype="string")
x = text_vectorizer(inputs)
x = embedding(x)
# x = layers.Bidirectional(layers.LSTM(64, return_sequences=True))(x)
x = layers.Bidirectional(layers.LSTM(64))(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_4 = tf.keras.Model(inputs, outputs, name="model_4_bidirectional")

In [56]:
# Get a summary
model_4.summary()

Model: "model_4_bidirectional"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_4 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 bidirectional (Bidirection  (None, 128)               98816
 al)

 dense_3 (Dense)             (None, 1)                 129

=================================================================
Total params: 1378945 (5.26 MB)
Trainable params: 1378945 (5.26 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [57]:
# Compile model
model_4.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

In [58]:
# Fit the model
model_4_hisrtory = model_4.fit(train_sentences,
                               train_labels,
                               epochs=5,
                               validation_data=(val_sentences, val_labels)
                               )

Epoch 1/5
215/215 [==============================] - 10s 30ms/step - loss: 0.1079 - accuracy: 0.9688 - val_loss: 1.0576 - val_accuracy: 0.7546
Epoch 2/5
215/215 [==============================] - 5s 24ms/step - loss: 0.0518 - accuracy: 0.9774 - val_loss: 1.2242 - val_accuracy: 0.7703
Epoch 3/5
215/215 [==============================] - 5s 25ms/step - loss: 0.0476 - accuracy: 0.9785 - val_loss: 1.2775 - val_accuracy: 0.7717
Epoch 4/5
215/215 [==============================] - 5s 25ms/step - loss: 0.0452 - accuracy: 0.9793 - val_loss: 1.4122 - val_accuracy: 0.7717
Epoch 5/5
215/215 [==============================] - 6s 27ms/step - loss: 0.0395 - accuracy: 0.9810 - val_loss: 1.4851 - val_accuracy: 0.7651

In [59]:
# Make predicitons with our bidirectional model
model_4_pred_probs = model_4.predict(val_sentences) 
model_4_pred_probs[:10]

24/24 [==============================] - 1s 4ms/step

array([[3.0544357e-04],
       [6.9035727e-01],
       [9.9998307e-01],
       [1.7242970e-01],
       [2.6034060e-05],
       [9.9974233e-01],
       [6.4702761e-01],
       [9.9999285e-01],
       [9.9998337e-01],
       [9.9781644e-01]], dtype=float32)

In [60]:
# Convert pred probs to pred labels
model_4_preds = tf.squeeze(tf.round(model_4_pred_probs))
model_4_preds[:10]

In [61]:
# Calculate the results of our bidirectional model
model_4_results = calculate_results(y_true=val_labels,
                                    y_pred=model_4_preds)
model_4_results

{'accuracy': 76.50918635170603,
 'precision': 0.7658125387191,
 'recall': 0.7650918635170604,
 'f1': 0.7634031052086162}

### Convolution Neural Networks for Text (and other types of sequences)

We've used CNNs for images are typically 2D (height x width)... however, our text data is 1D.
Previously we've Conv2D for our image data but now we're going to use Conv1D.
The typical structure of a COnv1D model for sequences (in our case text)

```
Inputs (text) -> Tokenization -> Embedding -> Layer(s) (typically Conv1D + pooling) -> Outputs (class probabilities)
```

### Model 5: Conv1D

In [62]:
# Test out our embedding layer, Con1D layer and max pooling 
from tensorflow.keras import layers
embedding_test = embedding(text_vectorizer(["this is a test sentence"]))
conv_1d = layers.Conv1D(filters=32,
                        kernel_size=5,
                        strides=1, # default  
                        activation="relu",
                        padding="same")
conv_1d_output = conv_1d(embedding_test) # pass test embedding through conv1d layer
max_pool = layers.GlobalMaxPool1D()
max_pool_output = max_pool(conv_1d_output) 
embedding_test.shape, conv_1d_output.shape, max_pool_output.shape

(TensorShape([1, 15, 128]), TensorShape([1, 15, 32]), TensorShape([1, 32]))

In [63]:
# Create 1-dimensional convolutional layer to model sequence
from tensorflow.keras import layers
inputs = layers.Input(shape=(1,), dtype=tf.string)
x = text_vectorizer(inputs)
x = embedding(x)
x = layers.Conv1D(filters=64, kernel_size=5, strides=1, activation="relu", padding="valid")(x)
x = layers.GlobalMaxPool1D()(x)
# x = layers.Dense(64, activation="relu")(x)
outputs = layers.Dense(1, activation="sigmoid")(x)
model_5 = tf.keras.Model(inputs, outputs, name="model_5_Conv1D")

# Compile Conv1D
model_5.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Get a summary of our Conv1D model
model_5.summary()

Model: "model_5_Conv1D"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_5 (InputLayer)        [(None, 1)]               0

 text_vectorization_1 (Text  (None, 15)                0
 Vectorization)

 embedding (Embedding)       (None, 15, 128)           1280000

 conv1d_1 (Conv1D)           (None, 11, 64)            41024

 global_max_pooling1d_1 (Gl  (None, 64)                0
 obalMaxPooling1D)

 dense_4 (Dense)             (None, 1)                 65

=================================================================
Total params: 1321089 (5.04 MB)
Trainable params: 1321089 (5.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [64]:
#  Fit the model
model_5_history = model_5.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
215/215 [==============================] - 6s 22ms/step - loss: 0.1281 - accuracy: 0.9575 - val_loss: 0.9087 - val_accuracy: 0.7677
Epoch 2/5
215/215 [==============================] - 4s 20ms/step - loss: 0.0744 - accuracy: 0.9740 - val_loss: 1.0237 - val_accuracy: 0.7612
Epoch 3/5
215/215 [==============================] - 4s 19ms/step - loss: 0.0624 - accuracy: 0.9766 - val_loss: 1.1715 - val_accuracy: 0.7598
Epoch 4/5
215/215 [==============================] - 4s 19ms/step - loss: 0.0563 - accuracy: 0.9769 - val_loss: 1.1580 - val_accuracy: 0.7598
Epoch 5/5
215/215 [==============================] - 4s 19ms/step - loss: 0.0507 - accuracy: 0.9778 - val_loss: 1.2710 - val_accuracy: 0.7533

In [65]:
# Make some predictions with our Conv1D model
model_5_pred_probs = model_5.predict(val_sentences)
model_5_pred_probs[:10]

24/24 [==============================] - 0s 2ms/step

array([[3.8397366e-01],
       [9.7608173e-01],
       [9.9997759e-01],
       [5.4993711e-02],
       [1.3323256e-08],
       [9.9648756e-01],
       [9.9109679e-01],
       [9.9999577e-01],
       [9.9999958e-01],
       [9.1234374e-01]], dtype=float32)

In [66]:
# Convert model 5 pred probs to labels
model_5_preds = tf.squeeze(tf.round(model_5_pred_probs))
model_5_preds[:10]

In [67]:
# Evaluate model 5 predicitons
model_5_results = calculate_results(y_true=val_labels,
                                    y_pred=model_5_preds)
model_5_results

{'accuracy': 75.32808398950131,
 'precision': 0.7529952160130181,
 'recall': 0.7532808398950132,
 'f1': 0.7522494297950951}

In [68]:
baseline_results

{'accuracy': 79.26509186351706,
 'precision': 0.8111390004213173,
 'recall': 0.7926509186351706,
 'f1': 0.7862189758049549}

## Model 6: TensorFlow Hub Pretrained sentence encoder

Now we've built a few of our models, let's try and use transfer learning for NLP, specifically using TensorFlow Hub's universal sentence encoder

In [69]:
import tensorflow_hub as hub
embed = hub.load("https://www.kaggle.com/models/google/universal-sentence-encoder/TensorFlow2/universal-sentence-encoder/2")
embed_samples = embed([sample_sentence,
                       "When you can the universal sentence encoder on a sentence, it turns it into numbers."])

print(embed_samples[0][:50])

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_estimator\python\estimator\util.py:74: The name tf.train.SessionRunHook is deprecated. Please use tf.estimator.SessionRunHook instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\saved_model_module.py:40: The name tf.saved_model.constants.LEGACY_INIT_OP_KEY is deprecated. Please use tf.compat.v1.saved_model.constants.LEGACY_INIT_OP_KEY instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\resolver.py:120: The name tf.gfile.MakeDirs is deprecated. Please use tf.io.gfile.makedirs instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\module_v2.py:120: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

WARNING:tensorflow:From c:\Users\Priyesh\AppData\Local\Programs\Python\Python311\Lib\site-packages\tensorflow_hub\module_v2.py:120: The name tf.saved_model.load_v2 is deprecated. Please use tf.compat.v2.saved_model.load instead.

tf.Tensor(
[-0.01157025  0.02485911  0.02878051 -0.012715    0.03971541  0.08827761
  0.02680988  0.05589838 -0.01068731 -0.00597293  0.00639321 -0.01819516
  0.00030816  0.09105889  0.05874645 -0.03180629  0.01512474 -0.05162925
  0.00991366 -0.06865345 -0.04209306  0.0267898   0.03011009  0.00321065
 -0.00337968 -0.04787356  0.0226672  -0.00985927 -0.04063615 -0.01292093
 -0.04666382  0.05630299 -0.03949255  0.00517682  0.02495827 -0.07014439
  0.0287151   0.0494768  -0.00633978 -0.08960193  0.02807119 -0.00808364
 -0.01360601  0.05998649 -0.10361788 -0.05195372  0.00232958 -0.02332531
 -0.03758106  0.03327729], shape=(50,), dtype=float32)

In [70]:
embed_samples[0].shape

TensorShape([512])

In [71]:
# Create a keras layer using the USE pretrained layer from tensorflow hub
sentence_encoder_layer = hub.KerasLayer("https://www.kaggle.com/models/google/universal-sentence-encoder/TensorFlow2/universal-sentence-encoder/2", 
                                        input_shape=[],
                                        dtype=tf.string,
                                        trainable=False,
                                        name="USE")

In [72]:
# Create model using the Sequential API
model_6 = tf.keras.Sequential([
    sentence_encoder_layer,
    layers.Dense(64, activation="relu"),
    layers.Dense(1, activation="sigmoid")
], name="model_6_USE")

# Compile 
model_6.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

model_6.summary()

Model: "model_6_USE"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 USE (KerasLayer)            (None, 512)               256797824

 dense_5 (Dense)             (None, 64)                32832

 dense_6 (Dense)             (None, 1)                 65

=================================================================
Total params: 256830721 (979.73 MB)
Trainable params: 32897 (128.50 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________

In [73]:
# Train a classifier on top of USE pretrained embeddings
model_6_history = model_6.fit(train_sentences,
                              train_labels,
                              epochs=5,
                              validation_data=(val_sentences, val_labels),
                              )

Epoch 1/5
215/215 [==============================] - 6s 11ms/step - loss: 0.5072 - accuracy: 0.7873 - val_loss: 0.4458 - val_accuracy: 0.8018
Epoch 2/5
215/215 [==============================] - 2s 8ms/step - loss: 0.4146 - accuracy: 0.8139 - val_loss: 0.4373 - val_accuracy: 0.8005
Epoch 3/5
215/215 [==============================] - 2s 8ms/step - loss: 0.4011 - accuracy: 0.8238 - val_loss: 0.4340 - val_accuracy: 0.8163
Epoch 4/5
215/215 [==============================] - 2s 8ms/step - loss: 0.3933 - accuracy: 0.8267 - val_loss: 0.4261 - val_accuracy: 0.8084
Epoch 5/5
215/215 [==============================] - 2s 7ms/step - loss: 0.3873 - accuracy: 0.8279 - val_loss: 0.4247 - val_accuracy: 0.8097

In [74]:
# make predictions with USE TF Hub model
model_6_pred_probs = model_6.predict(val_sentences)
model_6_pred_probs[:10]

24/24 [==============================] - 1s 7ms/step

array([[0.17883751],
       [0.8224782 ],
       [0.9920923 ],
       [0.22426298],
       [0.75517696],
       [0.7585818 ],
       [0.9860256 ],
       [0.98262095],
       [0.9533721 ],
       [0.09354764]], dtype=float32)

In [75]:
# Convert prediction probabilities to labels 
model_6_preds = tf.squeeze(tf.round(model_6_pred_probs))
model_6_preds[:10]

In [76]:
# Calculate model 6 performance metrics
model_6_results = calculate_results(y_true=val_labels,
                                    y_pred=model_6_preds)
model_6_results

{'accuracy': 80.97112860892388,
 'precision': 0.8102657904474438,
 'recall': 0.8097112860892388,
 'f1': 0.808794162258813}

In [77]:
len(train_data_shuffled)

7613

## Model 7: TF Hub Pretrained USE but with 10% of training data
Transfer learning really helps when you don't have a large dataset.
To see how our model performs on a smaller dataset, let's replicate model_6 except we'll train it on 10% of the data.

In [78]:
# Create subsets of 10% of the training data
train_10_percent = train_data_shuffled[["text", "target"]].sample(frac=0.1, random_state=42)
train_sentences_10_percent = train_10_percent["text"].to_list()
train_labels_10_percent = train_10_percent["target"].to_list()
len(train_sentences_10_percent), len(train_labels_10_percent)

(761, 761)

In [79]:
# Check the number of targets in our subset of data
train_10_percent["target"].value_counts()

target
0    413
1    348
Name: count, dtype: int64

In [80]:
train_data_shuffled["target"].value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [97]:
# Let's built a model the same as model_6
model_7 = tf.keras.models.clone_model(model_6)

# Compile the model
model_7.compile(loss="binary_crossentropy",
                optimizer=tf.keras.optimizers.Adam(),
                metrics=["accuracy"])

# Get a summary 
model_7.summary()

Model: "model_6_USE"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 USE (KerasLayer)            (None, 512)               256797824

 dense_5 (Dense)             (None, 64)                32832

 dense_6 (Dense)             (None, 1)                 65

=================================================================
Total params: 256830721 (979.73 MB)
Trainable params: 32897 (128.50 KB)
Non-trainable params: 256797824 (979.61 MB)
_________________________________________________________________

In [98]:
# Fit the model to the 10% training data subsets
model_7_history = model_7.fit(train_sentences_10_percent,
                              train_labels_10_percent,
                              epochs=5,
                              validation_data=(val_sentences, val_labels))

Epoch 1/5
22/22 [==============================] - 4s 40ms/step - loss: 0.6620 - accuracy: 0.7124 - val_loss: 0.6403 - val_accuracy: 0.7480
Epoch 2/5
22/22 [==============================] - 0s 13ms/step - loss: 0.5897 - accuracy: 0.7956 - val_loss: 0.5849 - val_accuracy: 0.7533
Epoch 3/5
22/22 [==============================] - 0s 15ms/step - loss: 0.5140 - accuracy: 0.8088 - val_loss: 0.5319 - val_accuracy: 0.7808
Epoch 4/5
22/22 [==============================] - 0s 13ms/step - loss: 0.4569 - accuracy: 0.8277 - val_loss: 0.5013 - val_accuracy: 0.7730
Epoch 5/5
22/22 [==============================] - 0s 13ms/step - loss: 0.4196 - accuracy: 0.8350 - val_loss: 0.4893 - val_accuracy: 0.7756

In [99]:
# Make precitions with the model trained on 10% of the data
model_7_pred_probs = model_7.predict(val_sentences)
model_7_pred_probs[:10]

24/24 [==============================] - 1s 9ms/step

array([[0.2149193 ],
       [0.5858913 ],
       [0.9078345 ],
       [0.416537  ],
       [0.5839183 ],
       [0.7181138 ],
       [0.8873019 ],
       [0.8106693 ],
       [0.8564586 ],
       [0.15968569]], dtype=float32)

In [100]:
# Turn pred probs into labels
model_7_preds = tf.squeeze(tf.round(model_7_pred_probs))
model_7_preds[:10]

In [101]:
# Evaluate model_7 predictions
model_7_results = calculate_results(y_true=val_labels,
                                    y_pred=model_7_preds)
model_7_results

{'accuracy': 77.55905511811024,
 'precision': 0.776326889347514,
 'recall': 0.7755905511811023,
 'f1': 0.7740902496040959}

In [95]:
model_6_results

{'accuracy': 80.97112860892388,
 'precision': 0.8102657904474438,
 'recall': 0.8097112860892388,
 'f1': 0.808794162258813}

In [96]:
# Making a better dataset split (no data leakage)
train_10_percent_split = int(0.1 * len(train_sentences))
train_sentences_10_percent = train_sentences[:train_10_percent_split]
train_labels_10_percent = train_labels[:train_10_percent_split]
len(train_labels_10_percent)

685

In [92]:
import numpy as np
pd.Series(np.array(train_labels_10_percent)).value_counts()

0    406
1    279
Name: count, dtype: int64